### ISSUE TITLE
Hybrid Infobox & Mappings extractor

### ISSUE THREAD

**Issue by jimkont** [dbpedia/extraction-framework#22]
Create a combination of infobox & mapping extractor.
Infobox extracts very raw data that in many cases have errors but can be useful if no mapping exists for the extracted template.

The new extractor should extract this raw data only if a mapping does not exists

**Comment by aditya-nambiar** [comment]
Hi, I would like to take up this task. Can you give a few examples of wikipedia pages which I could use .

**Comment by jimkont** [comment]
You can try with articles that use the Infobox_Person template
https://en.wikipedia.org/wiki/Special:WhatLinksHere/Template:Infobox_person?limit=500&namespace=0

e.g. in page http://dbpedia.org/page/Aristotle
we have `dbo:*` properties that come from the `MappingsExtractor` and `dbp:*` properties that come from the `InfoboxExtractor`
some of the triples extracted overlap, e.g. `dbp:placeOfBirth` vs `dbo:deathPlace` and the idea is to keep only the `dbo` in those cases

**Comment by jimkont** [comment]
A way to achieve this is to create a new meta extractor that runs both the `MappingExtractor` and the `InfoboxExtractor` and tries to remove the triples from the `InfoboxExtractor` that are mapped from the `MappingExtractor`.

In general this is not an easy task but we can use the `Quad` context to hack our way. In the context we store the line in wikitext a triple was extracted and in some other cases, [other info as well](https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/mappings/SimplePropertyMapping.scala#L235-L240).

Since we can have multiple properties of a template on the same line, the line alone cannot be used but, if we stored the template and the template property in the context too then we would have enough information to locate duplicate facts.

The workflow in the new meta extractor would be something like

1.  Extract the page with the `MappingExtractor` and get all quads
1.  For every quad we get, get the context `q1=(line, template name, property name)` and store it in a set `Mapped`
1.  Extract the page with the `InfoboxExtractor` and get all quads
1.  For every quad we get, we the context `q2=(line, template name, property name)` and accept the quad to the output only `Mapped` does not contain `q2`
