### ISSUE TITLE
remove scala.util.parsing.json dependencies (deprecated)

### ISSUE THREAD

**Issue by jimkont** [dbpedia/extraction-framework#277]
in scala 2.11 `scala.util.parsing.json` is deprecated and should be replaced with another library, probably the one that will be used for the JsonExtractor.

Once resolved we should remove the following dependency from live/pom.xml:
```
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-parser-combinators</artifactId>
            <version>2.11.0-M4</version>
        </dependency>
```

**Comment by adrapereira** [comment]
Hello, I'm a student from Portugal looking to participate in GSoC. I was thinking of fixing this bug in order to warm up. What do you think of using [json4s](https://github.com/json4s/json4s) ?

**Comment by jimkont** [comment]
Welcome @adrapereira!
Actually we already have a dependency on Jackson in core module and would make more sense to use  jackson-module-scala.

Haven't tried it personally but if jackson doesn't work then our only requirement is for the new library to exist in maven central repo

**Comment by adrapereira** [comment]
I'll look into jackson-module-scala then. Thank you!

**Comment by adrapereira** [comment]
I'm trying to run dbpedia live, following [this guide](https://github.com/dbpedia/extraction-framework/wiki/DBpedia-live), and already have a wikipedia copy running, but I'm stuck in the "Setup OAI" part. Is there any way you can help me?

**Comment by jimkont** [comment]
Well, starting Live can become a warm-up task of it's own :) If you don't
plan to apply for the DBpedia Live project I'd suggest to create a test for
validating your changes and I can provide sample input/output data.
Otherwise we can give you instructions on how to work on this

**Comment by adrapereira** [comment]
I chose this warm-up task exactly because I'm planning to apply for the "DBpedia Live scaling & new interface" project. It would be great if I could have Live up and running.

**Comment by jimkont** [comment]
great! ping me offline to give access to OAI but either way it will be much
easier if you use a test to change this

On Thu, Mar 5, 2015 at 9:23 AM, Andre Pereira <notifications@github.com>
wrote:

> I chose this warm-up task exactly because I'm planning to apply for the
> "DBpedia Live scaling & new interface" project. It would be great if I
> could have Live up and running.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dbpedia/extraction-framework/issues/277#issuecomment-77318483>
> .
>



-- 
Kontokostas Dimitris

**Comment by jimkont** [comment]
Here's some sample json data for the tests
https://gist.github.com/jimkont/f4bb74a78d4f2340ba60
