### ISSUE TITLE
object property extractor should check rdfs:range

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#286]
Consider dbo:firstAccentPerson, which declares rdfs:range dbo:Person.
The object property extractor does not check range when extracting, so it extracts any link that people have used, and a lot of them are not people:
- bg.dbp:Лхотце: 18_май and 1956: these are "event list" pages that someone linked instead of providing a plain date
- dbp:Abi_Gamin: United_Kingdom and Switzerland (it was a mixed British-Swiss expedition)
- dbp:Gunung_Tok_Wan: Kajang (a location), because someone wrote "A small group from Kajang Prison Officer". 
- dbp:Stawamus_Squaw: dbp:Prehistory, because someone mentioned when it was first climbed (a HistoricPeriod)

There are many other examples, eg check with this query:
```
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
select * {?x dbo:parent ?y
    filter not exists{?y a dbo:Person}}
```
and you'll find many strange values for dbo:parent, such as Archbishop, Corfu, All My Children, Adoption, etc. You can find all exceptions with a query like this, but it's too expensive for the public endpoint:
```
select ?x ?p ?y {
  ?x ?p ?y.
  filter exists {?p rdfs:range ?c. ?c rdfs:subClassOf owl:Thing
      filter not exists{?y a ?c}}}
```
We intend to find and publish a list of exceptions and analyze some of the root causes.

I think this is the single most important improvement that can greatly increase the quality of DBpedia data. The way it is now, RDFS domain & range reasoning has disastrous results.

**Comment by jimkont** [comment]
fixed with `TypeConsistencyCheck` script

**Comment by VladimirAlexiev** [comment]
I'm not sure this is fixed:
- dbr:Gunung_Tok_Wan indeed doesn't have dbo:firstAscentPerson anymore. But dbr:Stawamus_Squaw still has dbr:Prehistoric
- try [this query](http://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=select+*+%7B%3Fx+dbo%3Aparent+%3Fy%0D%0A++++filter+not+exists%7B%3Fy+a+dbo%3APerson%7D%7D&format=text%2Fhtml&CXML_redir_for_subjs=121&CXML_redir_for_hrefs=&timeout=30000&debug=on&run=+Run+Query+) `select * {?x dbo:parent ?y filter not exists{?y a dbo:Person}}`: there are tons of objects that are not Persons, eg
http://dbpedia.org/resource/Adoption
http://dbpedia.org/resource/Archbishop
http://dbpedia.org/resource/Billung (house)
http://dbpedia.org/resource/Billung
http://dbpedia.org/resource/Dairy
http://dbpedia.org/resource/House_of_Este
http://dbpedia.org/resource/House_of_Wittelsbach
http://dbpedia.org/resource/Prince
http://dbpedia.org/resource/Prince
http://dbpedia.org/resource/Prince
http://dbpedia.org/resource/Rabbi
http://dbpedia.org/resource/Rabbi
http://dbpedia.org/resource/Rabbi
http://dbpedia.org/resource/Rabbi
http://dbpedia.org/resource/Rabbi
http://dbpedia.org/resource/Soldier
- The first row is ridiculous, it says dbr:Murder_of_Nubia_Barahona had parent Adoption. DBpedia is not to blame, someone used infobox Person for dbr:Murder_of_Nubia_Barahona (guess the only notable thing about this kid was that she was murdered). I'll try to fix this
- MOST importantly: do we dare throw away objects that don't satisfy the range restriction?  There are very many persons in that list that are not marked as dbo:Person:
Ivan_Asen_II, Mary_Sidgwick_Benson, Al-Qa'im_Bi-Amrillah, Albert_Vogel,_Sr., Amancio_Ortega_Gaona, Anna_of_Austria_(1528–1590), Baron_Ferrers_of_Groby, Basina,_Queen_of_Thuringia

**Comment by VladimirAlexiev** [comment]
See https://github.com/dbpedia/extraction-framework/issues/516 about monarch/royalty, and in particular `dbr:Ivan_Asen_II`

**Comment by jimkont** [comment]
Vladimir, there is a script in place that does these checks but we left it
lenient on purpose.

What is rejected is objects with range that is disjoint with the expected
range.
But even this is not thrown away but placed on a separate dataset (called
mapping based disjoint).

Iirc, what is left is untyped entities and entities of the same ontology
sub tree e.g. doctor / athlete.

If you feel there is another case that always leads to errors, it could be
easily added to the workflow
