### ISSUE TITLE
extractionSamples/ doesn't work with non-ASCII characters in template name

### ISSUE THREAD

**Issue by jcsahnwaldt** [dbpedia/extraction-framework#289]
Probably an encoding problem. For example, Mapping_de:Infobox_Fluss works, but Mapping_de:Infobox_Straße doesn't return any data:

http://mappings.dbpedia.org/server/mappings/de/extractionSamples/Mapping_de:Infobox_Fluss
http://mappings.dbpedia.org/server/mappings/de/extractionSamples/Mapping_de:Infobox_Stra%C3%9Fe

I'd like to try to fix this. Could someone give me ssh access to the server, so I can read the logs? Please send me a message. Thanks!

**Comment by VladimirAlexiev** [comment]
Thanks for fixing this!!
