### ISSUE TITLE
drop TTL / TQL export, use only NT / NQ, use UTF-8

### ISSUE THREAD

**Issue by jcsahnwaldt** [dbpedia/extraction-framework#291]
Since NT (N-Triples) and NQ (N-Quads) files can officially be UTF-8 encoded (not just ASCII) since 25 February 2014, we might as well drop the TTL (Turtle) and TQL (Turtle Quads) export formats.

NT and NQ used to allow only ASCII, everything else had to be escaped like this: `\u12AB`. This meant that the DBpedia NT and NQ files were not human-readable for most non-Latin languages. That's why we introduced the TTL and TQL files. They used the same simple format as the NT and NQ files (no Turtle features like prefixes), the only difference was that they were UTF-8 encoded, not ASCII.

W3C specifications for NT and NQ from 25 February 2014:
http://www.w3.org/TR/n-triples/#n-triples-changes
http://www.w3.org/TR/n-quads/

**TODO: Make sure that Virtuoso and most other RDF frameworks can actually handle the new NT / NQ encoding.**

Implementation:
* Remove `"turtle-triples"` and `"turtle-quads"` from [UriPolicy](https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/destinations/formatters/UriPolicy.scala)
* Remove the `turtle` parameter from [TerseFormatter](https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/destinations/formatters/TerseFormatter.scala) and [TerseBuilder](https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/destinations/formatters/TerseBuilder.scala)
* Remove the `turtle` parameter from all methods and classes in [TurtleUtils](https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/util/TurtleUtils.scala), rename everything from `Turtle` to `NTriples` or so
* Check the specs: which chars need to be escaped? If it's only ch<0x20 and 0x7F<=ch<0xA0, then `TurtleUtils.escapeTurtle(code: Int)` can be simplified as follows. Replace these lines:
```
else if (code >= 0x0020 && code < 0x007F) sb append code.toChar
else if (turtle && code >= 0x00A0 && code <= 0xFFFF) sb append code.toChar
else if (turtle && code >= 0x10000) sb appendCodePoint code
else if (code <= 0xFFFF) appendHex('u', code, 4)
else appendHex('U', code, 8)
```
by this:
```
else if (code >= 0x0020 && code < 0x007F) sb append code.toChar
else if (code >= 0x00A0 && code <= 0xFFFF) sb append code.toChar
else if (code >= 0x10000) sb appendCodePoint code
else appendHex('u', code, 4)
```
or by something even shorter...
* Maybe inline `TurtleUtils.appendHex()` into `TurtleUtils.escapeTurtle(code: Int)`, it's only used once
* Even better: use a lookup table for the few code points that need to be escaped, e.g. an array that contains the string `\n` for index `0x0A`, `\u007F` for index `0x7F`, `\u0080` for index `0x80`, etc.
* File encoding for both formats was always UTF-8, so there's no need to change anything here. (UTF-8 also worked for NT/NQ because they didn't contain any non-ASCII chars, which meant that UTF-8 encoding was identical to ASCII encoding.)
* Remove all references to `turtle-triples`, `turtle-quads`, `ttl`, `tql` from all `extraction.*.properties` files in [dump](https://github.com/dbpedia/extraction-framework/tree/master/dump)
* Update Wiki page [Serialization-format-properties](https://github.com/dbpedia/extraction-framework/wiki/Serialization-format-properties)
* Save several hundred gigabytes on the download server. :-)
* Consider re-encoding old NT/NQ files on the download server and deleting the TTL/TQL files to save a few terabytes.
* I very likely forgot something important. ;-)

**Comment by jimkont** [comment]
For the next release we plan to create only ttl with IRI files. This will save some confusion between URIs / IRIs and avoid any stalled NT parsers so this will be indirectly solved
