### ISSUE TITLE
Invalid Unicode character representations in DBPedia 2014 long abstracts

### ISSUE THREAD

**Issue by slbayer** [dbpedia/extraction-framework#302]
This is probably similar to issue 273. 

http://dbpedia.org/resource/Close-mid_back_unrounded_vowel - contains \u followed by a space.
http://dbpedia.org/resource/Taiwanese_kana - see issue 273
http://dbpedia.org/resource/Ga%C5%A1per_Vidmar - contains \u followed by a space
http://dbpedia.org/resource/Pchery - invalid sequence \u02C (I think)
http://dbpedia.org/resource/L%C3%AA_V%C4%83n_Kh%C3%B4i - \u followed by a space
http://dbpedia.org/resource/Danish_national_road_21 - invalid sequence \u00B (I think)
http://dbpedia.org/resource/Walsh_Knob - \u followed by a space
http://dbpedia.org/resource/Pennell_Coast - invalid sequence \u00E (I think)

Not bad, out of 4.1M abstracts. Thanks for this fabulous resource.

**Comment by Hronom** [comment]
Same for me

**Comment by jimkont** [comment]
fixed in latest version
