### ISSUE TITLE
Special date extraction from template, date-page

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#306]
Two widely used practices on bg.wikipedia  cause very many dates to be missed

## template call

Lili Ivanova (famous singer): https://bg.wikipedia.org/w/index.php?title=Лили_Иванова&action=edit
```
| роден_на             = {{дрг|1939|4|24|1}}
```

This uses template дрг (https://bg.wikipedia.org/wiki/Шаблон:Дата_на_раждане_и_години), which prints year, age and attaches a category (the last param "1"):
```
Роденa 24 април 1939 г.  (75 г.)
[[Категория:Родени през 1939 година]]
```

The extractor misses it: http://mappings.dbpedia.org/server/extraction/bg/extract?title=Лили_Иванова&revid=&format=turtle-triples&extractors=custom

Is it possible to add special parsing and extract dates out of these:
```
{{Дата на раждане и години|yyyy|m|d...}}
{{дрг|yyyy|m|d...}}
{{Дата на раждане|yyyy|m|d...}}
{{др|yyyy|m|d...}}
{{Дата на смърт и години|yyyy|m|d...}}
{{дсг|yyyy|m|d...}}
{{Дата на смърт|yyyy|m|d...}}
{{дс|yyyy|m|d...}}
```
where ... indicates additional optional parameters

## date-pages
Lhotse mountain: https://bg.wikipedia.org/w/index.php?title=Лхотце&action=edit
```
| първо изкачване = [[18 май]] [[1956]]
```

Instead of simple dates, this uses date-pages that collect events on that date, resp. year. These are manually maintained, eg
* https://bg.wikipedia.org/wiki/18_май: includes "first ascent of Lhotse"
* https://bg.wikipedia.org/wiki/1956: does not include "first ascent of Lhotse"

The extractor bungles it very badly: http://mappings.dbpedia.org/server/extraction/bg/extract?title=Лхотце&revid=&format=turtle-triples&extractors=custom
* the object property extractor makes `firstAscentPerson` https://bg.wikipedia.org/wiki/18_май. But that's a date-page not a person!
* the year extractor makes `firstAscentYear "0018"^^xsd:gYear`, i.e. uses the first digits it finds in the field. But that's the day not the year!

Is it possible to preprocess special forms `[[dd Month]]` and `[[yyyy]]` and remove the brackets (links) so they are parsed as dates?

**Comment by jimkont** [comment]
We define these configurations here
https://github.com/jimkont/extraction-framework/blob/idn_support/core/src/main/scala/org/dbpedia/extraction/config/dataparser/DateTimeParserConfig.scala

In the first part we define month names for each language and the last part date templates

**Comment by VladimirAlexiev** [comment]
Thanks! see https://github.com/jimkont/extraction-framework/pull/1

But will this also take care of '''date-pages'''?

**Comment by VladimirAlexiev** [comment]
See https://github.com/dbpedia/extraction-framework/pull/307. But how about **date-pages**?

**Comment by jimkont** [comment]
in general case it does for other languages as well

On Tue, Jan 13, 2015 at 12:56 PM, Vladimir Alexiev <notifications@github.com
> wrote:

> Thanks! see jimkont#1
> <https://github.com/jimkont/extraction-framework/pull/1>
>
> But will this also take care of '''date-pages'''?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dbpedia/extraction-framework/issues/306#issuecomment-69727643>
> .
>



-- 
Kontokostas Dimitris

**Comment by VladimirAlexiev** [comment]
So just by adding the name "май" for the month of May, it should parse all of `[[18 май]] [[1956]]` as a date?

**Comment by jimkont** [comment]
It should yes. If you want to be 100% sure we have dateParserTest.Scala
where you can add Bulgarian specific test cases

**Comment by VladimirAlexiev** [comment]
@boyan-simeonov Can you check **date-pages**? https://bg.wikipedia.org/wiki/Иван_Вазов uses this style for birth/death, and they are not extracted at http://bg.dbpedia.org/resource/bgdbr/Иван_Вазов

**Comment by VladimirAlexiev** [comment]
@boyan-simeonov My mistake: the source is:
```
| дата на раждане  = {{дата на раждане|1850|07|09|1}}
| дата на смърт    = {{дата на смърт и години|1921|9|22|1850|7|9|1}}
```
Boyan, we have those configured. Please check what's going on? Add test cases as suggested by Dimitris above, and rerun the extraction

**Comment by VladimirAlexiev** [comment]
Ivan Vazov now sources birthDate/deathDate from Wikidata. There are no values in his infobox, and the relevant template https://bg.wikipedia.org/wiki/Шаблон:Личност says
```
роден-дата       = Дата на раждане [по подразбиране: стойност от Уикиданни]
i.e. birthDate  = birth date [by default: obtained from Wikidata]
```

It's not so easy to find persons with explicit birth date. Searching for `роден-дата` returns either:
- broken infoboxes, eg https://bg.wikipedia.org/wiki/Кубрат_Пулев, or 
- wicked pages where there's a table instead of an infobox, eg https://bg.wikipedia.org/wiki/Валтер_Рьорл
