### ISSUE TITLE
Build fail after fresh checkout 

### ISSUE THREAD

**Issue by boyan-simeonov** [dbpedia/extraction-framework#309]
After fresh checkout this morning I can't build the extraction framework. It seems that some of the maven dependencies are missing.  I get the following message from maven:

[WARNING] The POM for com.openlink.virtuoso:virtjdbc4:jar:7.0.0 is missing, no dependency information available
[WARNING] The POM for org.aksw.commons:model:jar:0.4 is missing, no dependency information available
[WARNING] The artifact ant: ant:jar:1.7.0 has been relocated to org.apache.ant: ant:jar:1.7.0

**Comment by jimkont** [comment]
there is a problem in the maven repo but this error is only for the live
module
so all other modules compile fine if you need to perform e.g. a dump
extraction

On Wed, Jan 14, 2015 at 11:33 AM, boyan-simeonov <notifications@github.com>
wrote:

> After fresh checkout this morning I cant build the extraction framework.
> It seems that some of the maven dependencies are missing. I get the
> following message from maven:
>
> [WARNING] The POM for com.openlink.virtuoso:virtjdbc4:jar:7.0.0 is
> missing, no dependency information available
> [WARNING] The POM for org.aksw.commons:model:jar:0.4 is missing, no
> dependency information available
> [WARNING] The artifact ant[image: :ant:]jar:1.7.0 has been relocated to
> org.apache.ant[image: :ant:]jar:1.7.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dbpedia/extraction-framework/issues/309>.
>



-- 
Kontokostas Dimitris
