### ISSUE TITLE
BG place coordinates lack precision

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#313]
Priority: MAJOR (how can I set priorities here?)

See this [wiki page](https://bg.wikipedia.org/w/index.php?title=София&action=edit):
```
| сев-ширина        = 42.697556
| изт-дължина       = 23.323638
```

See the corresponding [extraction](http://mappings.dbpedia.org/server/extraction/bg/extract?format=turtle-triples&extractors=custom&title=София)
```
<http://bg.dbpedia.org/resource/София> <http://bg.dbpedia.org/property/севШирина> "42"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://bg.dbpedia.org/resource/София> <http://bg.dbpedia.org/property/изтДължина> "23"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://bg.dbpedia.org/resource/София> <http://www.w3.org/2003/01/geo/wgs84_pos#lat> "42.0"^^<http://www.w3.org/2001/XMLSchema#float> .
<http://bg.dbpedia.org/resource/София> <http://www.w3.org/2003/01/geo/wgs84_pos#long> "23.0"^^<http://www.w3.org/2001/XMLSchema#float> .
```

The coordinates are first truncated to integers, then completed to a float with 0 decimals. Not enough: this designates a huge square area on the grid :-)

Do we need to somehow tell it which are floating numbers, in addition to the mapping 
http://mappings.dbpedia.org/index.php?title=Mapping_bg:Селище_в_България&action=edit
```
{{ GeocoordinatesMapping | latitude = сев-ширина | longitude = изт-дължина }}
```

**Comment by VladimirAlexiev** [comment]
For clarity, the raw literal extractor stops at the decimal point and extracts:
```
севШирина "42"^^xsd:integer; изтДължина "23"^^xsd:integer
```
It's all downhill from there: GeocoordinatesMapping knows it needs a float, but cannot restore the precision.

In contrast, the `{coord}}` extractor works perfectly, eg https://bg.wikipedia.org/w/index.php?title=Телевизионна_кула_София&action=edit
```
{{coord|42|40|36.32 ...
```
http://mappings.dbpedia.org/server/extraction/bg/extract?format=turtle-triples&extractors=custom&title=Телевизионна_кула_София:
```
lat 42.67675555555556
```
And I checked with a calculator:
```
42+40/60+36.32/60/60=42.676755555555555555555555555556  <<< right
42+40/60+36   /60/60=42.676666666666666666666666666667  <<< truncated seconds
```

**Comment by VladimirAlexiev** [comment]
Enwiki has this https://en.wikipedia.org/w/index.php?title=Sofia&action=edit:
```
|latd=42 |latm=42 |latNS=N
|longd=23 |longm=20 |longEW=E
```
Which is mapped to http://mappings.dbpedia.org/server/extraction/en/extract?format=turtle-triples&extractors=custom&title=Sofia
```
"42.7 23.333333333333332"
```
No precision is lost here, but only because the degrees&minutes given in the infobox are integers (and very imprecise at that!)

**Comment by jimkont** [comment]
I think https://github.com/dbpedia/extraction-framework/pull/299 solves this issue.
It's not deployed on the mapping server yet but you can pull and test this locally

**Comment by boyan-simeonov** [comment]
I will take care of this

**Comment by boyan-simeonov** [comment]
Today I performed some tests and it seems that #299 does not resolve our problem

**Comment by jimkont** [comment]
The problem comes with the different locale between Bulgarian and coordinate definition
The double parser expects a ',' for a decimal separator in bg wiki but '.' is given. #299 tries to fix some of these cases but of course it's not thorough enough for all cases.

Needs some further investigation on which part of the code the precision is lost. If you have some time for debugging GeoCoordinatesMapping  it would help a lot

**Comment by VladimirAlexiev** [comment]
It's not in GeoCoordinatesMapping, it's in the raw extractor.
Where is the locale info, and how can we adjust it? I've never seen "," used as as decimal separator in bgwiki.

**Comment by jimkont** [comment]
Then I was wrong & we shouldn't care about the raw infobox extractor values.

About locale, the extraction framework uses the default locale for each language in order to parse doubles. You can test this by adding some bg values in DoubleParserTest.scala

**Comment by VladimirAlexiev** [comment]
I assume that the Geo extractor takes care of `{{coord|42|40|36.32`: that works fine.

This bug is about GeoCoordinatesMapping that assembles a coordinate from 2..6 raw doubles. The way these doubles are extracted should be improved.

If you use locale info that is predefined (eg in JRE libraries) and cannot be adjusted, I think that's a wrong design decision: bg.wiki users don't use "," as decimal separator, no matter what locale info says. To be sure [I've asked on bg.wiki](https://bg.wikipedia.org/wiki/%D0%A3%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F:%D0%A0%D0%B0%D0%B7%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%B8#.D0.94.D0.B5.D1.81.D0.B5.D1.82.D0.B8.D1.87.D0.BD.D0.B0_.D1.82.D0.BE.D1.87.D0.BA.D0.B0_.D0.B8.D0.BB.D0.B8_.D0.B7.D0.B0.D0.BF.D0.B5.D1.82.D0.B0.D1.8F.3F). 

BTW, I have some doubts that the locale is to blame: what does it interpret "." as? There's no locale symbol that means "truncate all following digits" ;-)

**Comment by jimkont** [comment]
There is a configuration for this in `ParserUtilsConfig.scala` -> `decimalSeparators`
Can you set this, add some tests in `DoubleParserTest.scala` and then try again?

**Comment by boyan-simeonov** [comment]
I added configuration about Bulgarian in ParserUtilsConfig.scala and now it looks that everything is fine. I also added tests cases in DoubleParserTest.scala.

**Comment by VladimirAlexiev** [comment]
https://bg.wikipedia.org/w/index.php?title=Кърджали&action=edit has a crazy mix:
```
| площ = 30,759       << comma
| сев-ширина=41.650   << dot
| изт-дължина=25.367  << dot
| sat=41.65,25.367    << TWO numbers. But we don't need them: same as above
```

So @boyan-simeonov, this proves we need to treat both comma and dot as decimal separator
