### ISSUE TITLE
Cannot dump output in JSON format

### ISSUE THREAD

**Issue by Mec-iS** [dbpedia/extraction-framework#318]
There is no way for dumping properly the JSOND retrieved with the `requests` python library from

    http://dbpedia.org/data/Sun.jsond

I tried different json libraries in python: json, simpleson. But the result is always:

    Traceback (most recent call last):
      File "/usr/lib/python3.3/site-packages/requests-2.2.1-py3.3.egg/requests/models.py", line 740, in json
        return json.loads(self.content.decode(encoding), **kwargs)
      File "/usr/lib/python3.3/site-packages/simplejson-3.6.5-py3.3-linux-x86_64.egg/simplejson/__init__.py", line 505, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.3/site-packages/simplejson-3.6.5-py3.3-linux-x86_64.egg/simplejson/decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "/usr/lib/python3.3/site-packages/simplejson-3.6.5-py3.3-linux-x86_64.egg/simplejson/decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.scanner.JSONDecodeError: Invalid \X escape sequence '\\': line 73 column 36 (char 11827)

**Comment by jcsahnwaldt** [comment]
Thanks for the report. You are right - the JSON document is invalid. It contains an invalid escape sequence. As far as I know, it is generated by Virtuoso, so Virtuoso should fix the way it emits Unicode escapes in JSON.

JSON only allows Unicode escapes with a **lowercase u** followed by **four** hexadecimal digits (encoding 16 bits). Many other languages (e.g. all major RDF formats) also allow escapes with an **uppercase U** followed by **eight** hex digits (encoding 32 bits). This is convenient for code points that don't fit into 16 bits, but in JSON, such code points must be encoded with *surrogate pairs* (yuck):

> To escape a code point that is not in the Basic Multilingual Plane, the character is represented as a twelve character sequence, encoding the UTF-16 surrogate pair. So for example, a string containing only the G clef character (U+1D11E) may be represented as "\uD834\uDD1E".

Source: [JSON ECMA standard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf), page 4

This is line 73 of http://dbpedia.org/data/Sun.jsond

    "http://got.dbpedia.org/resource/\U00010343\U00010330\U0001033F\U00010339\U0001033B" : { "http://www.w3.org/2002/07/owl#sameAs" : [ { "type" : "uri", "value" : "http://dbpedia.org/resource/Sun" } ] } ,

Column 36 contains the starting backslash of the following Unicode escape sequence:

    \U00010343

In Java, N-Triples etc., this is perfectly valid and represents the Unicode character [U+10343 GOTHIC LETTER SAUIL](http://www.fileformat.info/info/unicode/char/10343/index.htm). In JSON, it should be escaped as

    \uD800\uDF43

**Comment by jcsahnwaldt** [comment]
As a workaround, maybe there are tools that convert `\U` escapes into surrogate pair escapes. You could pre-process the invalid JSON document and feed the result into the JSON parser. I know that's not very convenient, but it may help you until the bug is fixed.

**Comment by lmorillas** [comment]
Mec-iS, use demjson for now

```
In [11]: sun = requests.get('http://dbpedia.org/data/Sun.jsond')

In [12]: sundoc = demjson.decode(sun.text)

In [13]: len(sundoc)
Out[13]: 265
```

It works for me

**Comment by Mec-iS** [comment]
Thanks to both. The excursion into text encoding is pretty useful.

By now I will try the @lmorillas solution, even if it will need to add another requirement to our library.

Regards and good job!

**Comment by lmorillas** [comment]
@Mec-iS, I think this should work too, so you don't need any new requirement

```
import requests
import codecs
import json

from codecs import raw_unicode_escape_decode
sun = requests.get('http://dbpedia.org/data/Sun.jsond')
doc = json.loads(raw_unicode_escape_decode(sun.text)[0])
```

lm

**Comment by Mec-iS** [comment]
Great. Thanks for the workaround!

**Comment by lmorillas** [comment]
Well, it's a workaround, but dbpedia should export a valid JSON as @jcsahnwaldt said.

 ```
$ jsonlint -s Sun.jsond 
Sun.jsond:73:35: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 73, column 35, offset 11827
   |  String started at line 73, column 2, offset 11794
Sun.jsond:73:45: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 73, column 45, offset 11837
   |  String started at line 73, column 2, offset 11794
Sun.jsond:73:55: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 73, column 55, offset 11847
   |  String started at line 73, column 2, offset 11794
Sun.jsond:73:65: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 73, column 65, offset 11857
   |  String started at line 73, column 2, offset 11794
Sun.jsond:73:75: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 73, column 75, offset 11867
   |  String started at line 73, column 2, offset 11794
Sun.jsond:287:67: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 287, column 67, offset 46164
   |  String started at line 287, column 34, offset 46131
Sun.jsond:287:77: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 287, column 77, offset 46174
   |  String started at line 287, column 34, offset 46131
Sun.jsond:287:87: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 287, column 87, offset 46184
   |  String started at line 287, column 34, offset 46131
Sun.jsond:287:97: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 287, column 97, offset 46194
   |  String started at line 287, column 34, offset 46131
Sun.jsond:287:107: Error: String escape code is not allowed in strict JSON: '\\U'
   |  At line 287, column 107, offset 46204
   |  String started at line 287, column 34, offset 46131
Sun.jsond: has errors
```

**Comment by Mec-iS** [comment]
Yep. Exactly, that was the starting problem I pointed out, but it's a problem of the Virtuoso Server not of the Extraction Framework in particular, as I understood from @jcsahnwaldt

I solved it by keeping a local copy of the Sun's json where I corrected manually the body of the response.

**Comment by IvanMikhailov** [comment]
The fix is written and tested, now it's on the usual route to the public repositories.
