### ISSUE TITLE
Extracted RDF's are less than expected. 

### ISSUE THREAD

**Issue by Bini12** [dbpedia/extraction-framework#330]
Hi All,

When I check the number of extracted triple in each feature (categories, label, ...), the number of extracted features are less than than from SQL dump.

Is there anyone have suggestion why this happen?

Thank you in advance.

**Comment by jimkont** [comment]
What do you mean less that the `SQL` sump, can you be more specific?

**Comment by Bini12** [comment]
sorry for the confusion. and let me put this way..

I've a complete dump based extraction and I try to check extracted RDFs quality. 
What best way to check the quality of RDFs in dump based extraction?

**Comment by jcsahnwaldt** [comment]
I'm still confused. :-) "quality" is not very specific. Do you want to check if your extraction worked as expected?

**Comment by Bini12** [comment]
Let me put in your way : ) How do I know the extraction work as expected?
I want just idea or any thought

**Comment by jcsahnwaldt** [comment]
Compare your files to similar files (same language, same extractor, same format) on wiki.dbpedia.org/Downloads2014 . They won't be identical (they are based on Wikipedia data from April/May ), but they should be similar.

If you have other questions, subscribe and write to https://lists.sourceforge.net/lists/listinfo/dbpedia-discussion .
