### ISSUE TITLE
SPARQL on dbpedia

### ISSUE THREAD

**Issue by anupam08cseuit** [dbpedia/extraction-framework#333]
Hi,

I am interested in extraction of companies details using
SPARQL on
dbpedia dump (enwiki-20150205-pages-articles.xml.bz2)

i executed extraction-default-properties that works fine
but  extraction-abstract-properties not giving any abstracted  data

Please find the below expected query we are looking for this kind of result from dbpedia dump (enwiki-20150205-pages-articles.xml.bz2)

http://dbpedia.org/snorql/?query=SELECT+*+WHERE+{%0D%0A%3Fsubject+rdf%3Atype+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FCompany%3E.%0D%0A%3Fsubject+rdfs%3Alabel+%3Flabel.%0D%0A%3Fsubject+rdfs%3Acomment+%3Fabstract.%0D%0AFILTER+%28lang%28%3Flabel%29+%3D+%22en%22+%26%26+lang%28%3Fabstract%29+%3D+%22en%22%29%0D%0A}+LIMIT+200%0D%0A

SELECT * WHERE {
?subject rdf:type <http://dbpedia.org/ontology/Company>.
?subject rdfs:label ?label.
?subject rdfs:comment ?abstract.
FILTER (lang(?label) = "en" && lang(?abstract) = "en")
} LIMIT 200

Thanks,
Anupam

**Comment by jimkont** [comment]
Abstracts are special and need a local wikipedia clone to work. See the instructions for details
https://github.com/dbpedia/extraction-framework/wiki/Extraction-Instructions#abstract-extraction
