### ISSUE TITLE
extracting {{#property}}-es from Wikidata 

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#334]
@jimkont What will it take to start extracting facts from Wikidata, when templates start using {{#property}}?
* I've heard itwiki is piloting the use of Wikidata
* A few days ago a prominent bgwiki admin (Spas Kolev) told me they're migrating Parent Places to Wikidata, which is a much better alternative to https://github.com/dbpedia/extraction-framework/issues/305

**Comment by jimkont** [comment]
We thought a lot about this and the easiest way is to extract wikidata
directly

That's why we started this project with Ali

**Comment by VladimirAlexiev** [comment]
Then it's a question of integrating the two data streams efficiently. Say we have these extracted triples from Wikipedia and Wikidata respectively (the P and Q numbers are made up)
* dbr:Paris dbo:country dbr:France // from enwiki
* wd:Q123 wd:P456 wd:Q678. // "Sofia has country Bulgaria" from wikidata

I could owl:sameAs the Q's, owl:equivalentProperty the P's and hope for the best. But:
* maybe I only want to use wd:P456 but not the other props of countries and cities. If I do, there'd be massive duplication of facts in the areas where DBpedia and Wikidata intersect
* maybe I only want to use it for entities extracted from bgwiki since enwiki doesn't yet use this `{{#property}}`

So it's a question of phasing or how to manage a transition: per property and per national wiki...

**Comment by tgalery** [comment]
Hi guys, sorry to barge in, but I was just wondering how the state of wikidata extraction is. Would wikidata extraction be able to generate more dbpedia ontology triples as compared to mappings of infobox properties ?

Also, I tried to run the extraction on a recent wikidata dump. After a few hours of processing which seemed to be going alright, I started to see a lot of those:

```
found by dbpedia:   [null].
found by wikipedia: [title=Q2898172;ns=0/Main/;language:wiki=wikidata,locale=en]
Oct 30, 2015 9:43:21 PM org.dbpedia.extraction.mappings.Redirects$ loadFromSource
INFO: Redirects loaded from source (wikidata)
```

Then finally I got something like this:

```
at org.dbpedia.extraction.dump.extract.ConfigLoader$$anonfun$getExtractionJobs$1.apply(ConfigLoader.scala:40)
	at org.dbpedia.extraction.dump.extract.ConfigLoader$$anonfun$getExtractionJobs$1.apply(ConfigLoader.scala:40)
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.immutable.RedBlackTree$TreeIterator.foreach(RedBlackTree.scala:468)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.IterableLike$$anon$1.foreach(IterableLike.scala:310)
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168)
	at scala.collection.IterableViewLike$$anon$3.foreach(IterableViewLike.scala:113)
	at org.dbpedia.extraction.dump.extract.Extraction$.main(Extraction.scala:30)
	at org.dbpedia.extraction.dump.extract.Extraction.main(Extraction.scala)
	... 6 more
Caused by: java.io.FileNotFoundException: config.json (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at scala.io.Source$.fromFile(Source.scala:91)
	at scala.io.Source$.fromFile(Source.scala:76)
	at scala.io.Source$.fromFile(Source.scala:54)
	at org.dbpedia.extraction.config.mappings.wikidata.JsonConfig.readConfiguration(WikidataExtractorConfigFactory.scala:40)
	at org.dbpedia.extraction.config.mappings.wikidata.JsonConfig.<init>(WikidataExtractorConfigFactory.scala:35)
	at org.dbpedia.extraction.config.mappings.wikidata.WikidataExtractorConfigFactory$.createConfig(WikidataExtractorConfigFactory.scala:28)
	at org.dbpedia.extraction.mappings.WikidataR2RExtractor.<init>(WikidataR2RExtractor.scala:54)
	... 30 more
```

Are there any detailed instructions on wikidata extraction that could help me bypass this error ?

**Comment by jimkont** [comment]
On Sat, Oct 31, 2015 at 4:14 AM, Thiago Galery <notifications@github.com>
wrote:

> Hi guys, sorry to barge in, but I was just wondering how the state of
> wikidata extraction is. Would wikidata extraction be able to generate more
> dbpedia ontology triples as compared to mappings of infobox properties ?
>
> Also, I tried to run the extraction on a recent wikidata dump. After a few
> hours of processing which seemed to be going alright, I started to see a
> lot of those:
>
> found by dbpedia:   [null].
> found by wikipedia: [title=Q2898172;ns=0/Main/;language:wiki=wikidata,locale=en]
> Oct 30, 2015 9:43:21 PM org.dbpedia.extraction.mappings.Redirects$ loadFromSource
> INFO: Redirects loaded from source (wikidata)
>
>
This step takes a while and is the redirect calculation step and happens
only the first time you pass the dump


> Then finally I got something like this:
>
> at org.dbpedia.extraction.dump.extract.ConfigLoader$$anonfun$getExtractionJobs$1.apply(ConfigLoader.scala:40)
>     at org.dbpedia.extraction.dump.extract.ConfigLoader$$anonfun$getExtractionJobs$1.apply(ConfigLoader.scala:40)
>     at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169)
>     at scala.collection.Iterator$class.foreach(Iterator.scala:743)
>     at scala.collection.immutable.RedBlackTree$TreeIterator.foreach(RedBlackTree.scala:468)
>     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
>     at scala.collection.IterableLike$$anon$1.foreach(IterableLike.scala:310)
>     at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168)
>     at scala.collection.IterableViewLike$$anon$3.foreach(IterableViewLike.scala:113)
>     at org.dbpedia.extraction.dump.extract.Extraction$.main(Extraction.scala:30)
>     at org.dbpedia.extraction.dump.extract.Extraction.main(Extraction.scala)
>     ... 6 more
> Caused by: java.io.FileNotFoundException: config.json (No such file or directory)
>     at java.io.FileInputStream.open(Native Method)
>     at java.io.FileInputStream.<init>(FileInputStream.java:146)
>     at scala.io.Source$.fromFile(Source.scala:91)
>     at scala.io.Source$.fromFile(Source.scala:76)
>     at scala.io.Source$.fromFile(Source.scala:54)
>     at org.dbpedia.extraction.config.mappings.wikidata.JsonConfig.readConfiguration(WikidataExtractorConfigFactory.scala:40)
>     at org.dbpedia.extraction.config.mappings.wikidata.JsonConfig.<init>(WikidataExtractorConfigFactory.scala:35)
>     at org.dbpedia.extraction.config.mappings.wikidata.WikidataExtractorConfigFactory$.createConfig(WikidataExtractorConfigFactory.scala:28)
>     at org.dbpedia.extraction.mappings.WikidataR2RExtractor.<init>(WikidataR2RExtractor.scala:54)
>     ... 30 more
>
> Are there any detailed instructions on wikidata extraction that could help
> me bypass this error ?
>
the file is here:
https://github.com/dbpedia/extraction-framework/blob/master/dump/config.json
It looks like a file permission / location issue, how do you start the
extraction and from which folder?


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dbpedia/extraction-framework/issues/334#issuecomment-152686964>
> .
>



-- 
Kontokostas Dimitris
