### ISSUE TITLE
enable aux templates with IntermediateNodeMapping

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#335]
Listen is an aux template that adds useful info to the page: in this case a soundRecording that's somehow relevant to the main subject.

I made a mapping at http://mappings.dbpedia.org/index.php?title=Mapping_en:Listen&action=edit as explained in https://github.com/dbpedia/mappings-tracker/issues/19 (see Turtle there).

Unfortunately this mapping is currently invalid, since the mapping language insists having mapToClass in the outer mapping. But soundRecording can be applied to any entity, so I can't know the class.

Please enable an "empty" outer mapping that is simply a container for a bunch of IntermediateNodeMappings. IMHO the easiest is to allow missing mapToClass if there is an embedded IntermediateNodeMapping.

**Comment by jimkont** [comment]
We use owl:Thing in this case, can you try that?

**Comment by VladimirAlexiev** [comment]
Thanks! Works perfectly, eg
http://mappings.dbpedia.org/server/extraction/bg/extract?title=Джон+Кенеди&revid=&format=turtle-triples&extractors=custom
