### ISSUE TITLE
Broken URL on DBpedia Live Wiki

### ISSUE THREAD

**Issue by hzengin** [dbpedia/extraction-framework#343]
At this [page](https://github.com/dbpedia/extraction-framework/wiki/DBpedia-live) there is a statement with a broken link that says " You can also use this shell script to download the latest dumps for your language."
The link heads to https://github.com/alexandrutodor/extraction-framework/blob/master/live/scripts/syncwiki/downloadDumps.sh which is broken.

There is also another broken link on chapter "Setup OAI"s last line, heads to https://github.com/alexandrutodor/extraction-framework/tree/master/live/scripts/syncwiki/wiki

**Comment by alexandrutodor** [comment]
Sorry, that's my bad, I was moving the scripts to gist. I fixed the links to the scripts and I'll move the preconfigured wiki into it's own repo tomorrow. 
@hzengin Btw, are you interested on configuring the live extraction for a specific language chapter. Because if so this would give me a change to test out a  docker image I've been working on.

**Comment by hzengin** [comment]
@alexandrutodor yes I am interested on it, I want to create a simple project with dbpedia and configuring the live extraction for English is essential for it, so I can test/use the image you've been working on

**Comment by alexandrutodor** [comment]
Well the docker image has everything pretty much configured, but it won't help you much without access to the wikipedia OAI-PMH stream. Do you have access to the change stream ?

**Comment by hzengin** [comment]
Opps, looks like I have missed something vital, I don't have access to it and I think sorrily this is end of story for live extraction for me

**Comment by jimkont** [comment]
If you want to experiment and contribute to Live you can have dev access to OAI but not for running your own project. This is only due to server limitations
