### ISSUE TITLE
http://dbpedia.org/page/Category:Companies_listed_on_Malawi_Stock_Exchange and similar do not list all entities

### ISSUE THREAD

**Issue by mbtyomkin** [dbpedia/extraction-framework#353]
Looking at some of the stock data on Wikipedia and dbPedia - the equivalent pages do not have same data.
Ex. 
http://dbpedia.org/page/Category:Companies_listed_on_Malawi_Stock_Exchange
http://en.wikipedia.org/wiki/Category:Companies_listed_on_Malawi_Stock_Exchange
Wikipedia lists 6 companies, yet dbPedia lists only 3.

**Comment by jimkont** [comment]
there were only 3 at the time this was extracted
e.g. [1] didn't have this category then

[1]
https://en.wikipedia.org/w/index.php?title=British-American_Investments_Company&action=edit&oldid=608360487

**Comment by mbtyomkin** [comment]
QQ: when will the next extraction occur? I did not see a schedule/frequency published.

**Comment by jimkont** [comment]
if everything goes well in April but you can extract your own DBpedia
version using this project
