### ISSUE TITLE
IntermediateNodeMapping too often skips node creation

### ISSUE THREAD

**Issue by Nono314** [dbpedia/extraction-framework#364]
There is a test [in the code] (https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/mappings/IntermediateNodeMapping.scala#L47) that checks that, when there are several properties, they should have exactly one value each.

I think this test is really overreaching, and should rather be `size <= 1` (the comment actually says "multiple properties"). IntermediateNode is increasingly used to group together a number of properties, some of which can of course be missing. With the current test, the node creation is skipped when not all properties are extracted, which Ieads to a loss of valuable data. 

This made me scratch my head quite a few times as a mapper, when not seeing in the extraction test page the nodes I was expecting, on a seemingly random basis from article to article.

Actually, even having only one property with several values should not be an issue. Confusion starts with at least 2 properties both having more than on value. The comment by @jcsahnwaldt says there were around 7000 such cases at the time, I guess there are many more now, a large part of which could be avoided and extract data.

**Comment by jimkont** [comment]
Didn't know that :)  
I cannot think of reasons to stick to that. @jcsahnwaldt any reasons why we made that choice?

**Comment by Nono314** [comment]
Extractions look way more complete for me with the update.
