### ISSUE TITLE
dbpedia-spotlight(#353): Adding New Surface Forms using bold mentions

### ISSUE THREAD

**Issue by abhishekg2389** [dbpedia/extraction-framework#381]
Hi all,

I am working on an issue in spotlight. Regarding which I want to extract bold text from the data. In files if any text is surrounded by triple single quotes then that text is bold. For this I checked out the code in extraction framework but I am unable to find any code for detecting bold text. So I would like to know if there already exist any code already to detect that?

**Comment by tgalery** [comment]
@jimkont maybe you should close this issue, since it is more related to dbpedia spotlight

**Comment by abhishekg2389** [comment]
Hi @tgalery and @jimkont,

Closing this issue as it is related to dbpedia spotlight.
