### ISSUE TITLE
Some dbo:abstract / rdfs:comment have coordinates in front

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#392]
The dbo:abstract / rdfs:comment of some cities, eg http://bg.dbpedia.org/resource/bgdbr/Одеса (Odessa) or http://bg.dbpedia.org/resource/bgdbr/Лондон (London) start with the coordinates repeated twice, eg:
*46.466667, 30.73333346.466667, 30.733333Одеса (на украински Одеса, на руски Одесса, на румънски Odesa) е черноморски град в Украйна...*

As you can see, the source of that page starts with an infobox that has these coordinates (but broken down into deg,min,sec): https://bg.wikipedia.org/w/index.php?title=Одеса&action=edit&oldid=6328404.

But how can the coordinates end up into the abstract???

**Comment by VladimirAlexiev** [comment]
София has these coordinates and the abstract doesn't have this bug:
```
| сев-ширина        = 42.697556
| изт-дължина       = 23.323638 
```
Варшава has these coordinates and the abstract has this bug:
```
| гео-ширина       = 52.217
| гео-дължина      = 21.033
```

Weirdness

**Comment by jimkont** [comment]
Can you check if you include this in the MW LocalSettings.php
```
$wgExtractsRemoveClasses = array_merge($wgExtractsRemoveClasses, array( '.metadata', 'span.coordinates', 'span.geo-multi-punct', 'span.geo-nondefault', '#coordinates', '.reflist', '.citation', '#toc', '.tocnumber', '.references', '.reference', '.noprint'));
```

**Comment by VladimirAlexiev** [comment]
@boyan-simeonov Please check

**Comment by jimkont** [comment]
@VladimirAlexiev @boyan-simeonov did this solve your issue? if so feel free to close:)

**Comment by VladimirAlexiev** [comment]
Checked the two cities mentioned above and they don' have the bug:
- http://mappings.dbpedia.org/server/extraction/bg/extract?title=Варшава+&revid=&format=turtle-triples&extractors=custom
- http://mappings.dbpedia.org/server/extraction/bg/extract?title=Лондон+&revid=&format=turtle-triples&extractors=custom
