### ISSUE TITLE
Data not appearing for URLs with single quotes

### ISSUE THREAD

**Issue by janinaj** [dbpedia/extraction-framework#393]
I am looking at this page in Wikipedia - http://en.wikipedia.org/wiki/Trelawny_of_the_'Wells'.

When I go to http://dbpedia.org/page/Trelawny_of_the_Wells, it redirects to http://dbpedia.org/page/Trelawny_of_the_'Wells', but the page has no information. Typing http://dbpedia.org/page/Trelawny_of_the_%27Wells%27 does not also work.

This query in SPARQL provides me with the extracted data:
    DESCRIBE <http://dbpedia.org/resource/Trelawny_of_the_'Wells'>

**Comment by kurzum** [comment]
@janinaj 
thanks for reporting

this seems fixed:
http://dbpedia.org/page/Trelawny_of_the_Wells
http://dbpedia.org/page/Trelawny_of_the_%27Wells%27

**Comment by pkleef** [comment]
This issue was already resolved in the previous dbpedia.org instance. 

I have re-tested these links in the latest version and the appear to be working correctly with the appropriate redirects happening.
