### ISSUE TITLE
dbo:spouse relationships are disappearing in DBpedia Live as they got reformatted in Wikipedia infoboxes

### ISSUE THREAD

**Issue by mgns** [dbpedia/extraction-framework#395]
dbo:spouse relationships are disappearing in DBpedia Live as they got reformatted in Wikipedia infoboxes, e.g.:
http://en.wikipedia.org/w/index.php?title=Samuel_L._Jackson&diff=prev&oldid=662795800
```
-
 | spouse           = [[LaTanya Richardson]] (1980–present) 
+
 | spouse           = {{marriage|[[LaTanya Richardson]]|1980}}
```

**Comment by alexandrutodor** [comment]
Looks like the old nested infobox issue.
