### ISSUE TITLE
Filenames containing parentheses are truncated

### ISSUE THREAD

**Issue by tomjaspers** [dbpedia/extraction-framework#396]
Best illustrated with an example: 

http://dbpedia.org/page/In_a_Bar,_Under_the_Sea has `DEUS - In A Bar, Under The Sea .gif` as its `dbpprop:cover`. The actual filename should be  `DEUS - In A Bar, Under The Sea (cover).gif`

Note the space character before the extension in the dbpprop.

I haven't checked if it is *only* parentheses that cause this (i.e., maybe some other characters cause the truncating too).

**Comment by jimkont** [comment]
Thanks @tomjaspers 
This triple comes from the raw infobox extractor (all triples from the dbpprop namespace) which guesses datatypes greedily and is considered of low quality in general.
you should rely more in triples inf the dbo / dbpedia-owl namespace
