### ISSUE TITLE
the test extractor is broken

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#399]
http://mappings.dbpedia.org/server/extraction/en/extract?title=Jimmy+Connors&revid=&format=turtle-triples&extractors=custom:
Exception:	org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.

This is rather urgent because we can't test mappings

**Comment by jimkont** [comment]
Should be related to a recent change the MW api
https://lists.wikimedia.org/pipermail/wikitech-l/2015-June/081931.html

**Comment by jimkont** [comment]
The actual problem was that Wikipedia moved the api from http to https

**Comment by nathanncohen** [comment]
Hello everybody! I see that this issue is 'closed', does that mean that live.dbpedia can be operational again? Thanks.

**Comment by jimkont** [comment]
the dependencies in Live were different but now fixed there too.
After some testing Live will start rolling again soon

**Comment by nathanncohen** [comment]
Great news! Is there some mailing list of <any location> where those matters are discussed? I joined dbpedia-discussion already but it does not seem to be the right place. Thanks again for your answer!
