### ISSUE TITLE
Minus sign (-) lost in datatype conversion (was: Incorrect extraction degrees Celsius -> Kelvin)

### ISSUE THREAD

**Issue by johanromme** [dbpedia/extraction-framework#401]
https://nl.wikipedia.org/wiki/Propeen says kookpunt(=boilingpoint) = -47.69
http://nl.dbpedia.org/page/Propeen says ChemicalSubstance/boilingpoint = 320.84
This incorrect value is calculated using 273.15 + 47.69 = 320.84
The correct value is something like 225K which is 273.15 - 47.69 = 225.46

**Comment by jimkont** [comment]
Hi, looking at this issue atm. The base unit in DBpedia is Kelvin and looks like the current calculations are correct
https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature

I close this for now but please re-open if I'm wrong on this

**Comment by johanromme** [comment]
Hi Dimitris,


I'm working in a chemical engineering company and from several
databases I get a boiling temperature of about 225.5 Kelvin for the
component with formula C6H6, CAS-number 115-07-1 and names:
- 'propylene' in English
- 'propeen' or 'propyleen' in Dutch
- 'Propen' or 'Propylen' in German
This 225.5 Kelvin corresponds to -47.65 Celsius.

This is confirmed by: http://chem.sis.nlm.nih.gov/chemidplus/rn/115-07-1
At the tab 'Physical Properties' it says -47.6 Celsius for the boiling point

(Minor differences can be considered correct with these physical properties)


If I now look at the Dutch wikipedia page: 
https://nl.wikipedia.org/wiki/Propeen
It says for the boiling point ('kookpunt' in Dutch) -47.69 Celsius which 
is correct.

If I then look at the Dutch dbpedia page: http://nl.dbpedia.org/page/Propeen
It says for the boiling point ( both 
http://dbpedia.org/ontology/boilingPoint and
http://dbpedia.org/ontology/ChemicalSubstance/boilingPoint) a value of 
320.84
which is in Kelvin.

This value of 320.84 is completely wrong.

The same is true for the German wikipedia page: 
https://de.wikipedia.org/wiki/Propen
(It says for the boiling point ('siedepunkt' in German) -47.7 Celsius 
which is also correct).
and the corresponding dbpedia page: http://de.dbpedia.org/page/Propen
which show a value of 320.85 (K) for the boiling point.

This value of 320.85 is also wrong.

It seems that the Celsius->Kelvin conversion in the extraction framework 
does not take
into account the minus sign before the temperature in Celsius.

The current calculation is: 273.15 + 47.69 (C) = 320.84 (K)

Where it should be: 273.15 - 47.69 (C) = 225.46 (K)

The same goes for the melting point where the errors are even bigger.


So the error is still there and I think it should be fixed, as not only 
the dutch
dbpedia is affected


best regards,
Johan.



On 09/30/2015 10:04 AM, Dimitris Kontokostas wrote:
>
> Hi, looking at this issue atm. The base unit in DBpedia is Kelvin and 
> looks like the current calculations are correct
> https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature
>
> I close this for now but please re-open if I'm wrong on this
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dbpedia/extraction-framework/issues/401#issuecomment-144320544>.
>

-- 

*Ir. Johan Romme*
/PROSYN expert/
*Process Design Center (PDC)*
Catharinastraat 21f, NL-4811 XD
Breda, The Netherlands
Tel: +31 (0)76 530 1908
Please note that our PO Box number and fax number no longer exist.
romme@process-design-center.com <mailto:romme@process-design-center.com>
www.process-design-center.com <http://www.process-design-center.com>

**Comment by jimkont** [comment]
Trying to follow the correct calculation here...
using this website http://www.metric-conversions.org/temperature/celsius-to-kelvin.htm
I get 47.69ºC= 320.8400K
and the types in Wikipedia have a plus sign not a minus
can you send me a reference for the types you refer to?

**Comment by johanromme** [comment]
If, in the website you mention, you type -47.69ºC you will get

-47.69ºC= 225.4600K

Please note the minus, temperatures in Celsius can be negative...

I do not know about types, I only know that dbpedia displays incorrect 
values.


On 09/30/2015 11:26 AM, Dimitris Kontokostas wrote:
>
> Trying to follow the correct calculation here...
> using this website 
> http://www.metric-conversions.org/temperature/celsius-to-kelvin.htm
> I get 47.69ºC= 320.8400K
> and the types in Wikipedia have a plus sign not a minus
> can you send me a reference for the types you refer to?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dbpedia/extraction-framework/issues/401#issuecomment-144337017>.
>

-- 

*Ir. Johan Romme*
/PROSYN expert/
*Process Design Center (PDC)*
Catharinastraat 21f, NL-4811 XD
Breda, The Netherlands
Tel: +31 (0)76 530 1908
Please note that our PO Box number and fax number no longer exist.
romme@process-design-center.com <mailto:romme@process-design-center.com>
www.process-design-center.com <http://www.process-design-center.com>

**Comment by jimkont** [comment]
I get it know, we have the correct type but the parser looses the minus (-)
sign

**Comment by johanromme** [comment]
Exactly



On 09/30/2015 12:05 PM, Dimitris Kontokostas wrote:
> I get it know, we have the correct type but the parser looses the 
> minus (-)
> sign
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dbpedia/extraction-framework/issues/401#issuecomment-144345287>.
>

-- 

*Ir. Johan Romme*
/PROSYN expert/
*Process Design Center (PDC)*
Catharinastraat 21f, NL-4811 XD
Breda, The Netherlands
Tel: +31 (0)76 530 1908
Please note that our PO Box number and fax number no longer exist.
romme@process-design-center.com <mailto:romme@process-design-center.com>
www.process-design-center.com <http://www.process-design-center.com>

**Comment by jimkont** [comment]
http://mappings.dbpedia.org/server/extraction/nl/extract?title=Propeen&revid=&format=trix&extractors=mappings

**Comment by johanromme** [comment]
Still not fixed, see: http://nl.dbpedia.org/page/Propeen
Boilingpoint(kookpunt) is 320.84 (Kelvin) on page which is incorrect.
The correct value is something like 225 Kelvin as described above.

**Comment by johanromme** [comment]
Hello Dimitris,


Maybe this issue can be re-opened again, as it is still not fixed.
Not even after the major dbpedia upgrade of the past few days.

The problem affects all chemical components with a melting,
boiling or critical temperature below zero Celsius. (Probably
also more extraction data involving kelvin/celsius conversions).


Regards,
Johan.




On 10/23/2015 06:44 PM, Dimitris Kontokostas wrote:
>
> Closed #401 
> <https://github.com/dbpedia/extraction-framework/issues/401> via 
> 5699d6e 
> <https://github.com/dbpedia/extraction-framework/commit/5699d6eb2e111c89268d0f4526c15b1130f33aa2>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dbpedia/extraction-framework/issues/401#event-444009150>.
>

-- 

*Ir. Johan Romme*
/PROSYN expert/
*Process Design Center (PDC)*
Catharinastraat 21f, NL-4811 XD
Breda, The Netherlands
Tel: +31 (0)76 530 1908
Please note that our PO Box number and fax number no longer exist.
romme@process-design-center.com <mailto:romme@process-design-center.com>
www.process-design-center.com <http://www.process-design-center.com>

**Comment by johanromme** [comment]
Just noticed that the german dbpedia page (http://de.dbpedia.org/page/Propen) now displays a correct value of 225.45 Kelvin. 
Infortunately the dutch dbpedia page (http://nl.dbpedia.org/page/Propeen) still shows the incorrect value of 320.84 Kelvin.

**Comment by jimkont** [comment]
Thanks @johanromme 
I think this can be closed now

**Comment by johanromme** [comment]
Seems OK now, Thanks
