### ISSUE TITLE
Missing categories in DBPedia

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [dbpedia/extraction-framework#403]
I have observed that DBPedia is missing categories in the ```Categories (Skos)``` dataset compared to the data available in Wikipedia.

If you look at the following page:

https://en.wikipedia.org/wiki/Category:1st-century_births

it's categories are: ```1st century / Births by year / 1st-century people```

now if you look at the corresponding DBPedia page:

http://dbpedia.org/page/Category:1st-century_births

you can see that it only has a single of those three categories: ```category:1st-century_people```.

If you closer at the Wikipedia page's source markup:

```
{{BirthsInCentury|0}}
{{Commons category|1st-century births}}

[[Category:1st-century people]]
```

which if I understand correctly says that the page should have all the categories of ```Category:1st-century people``` but also inherit it's parent template ```BirthsInCentury```'s categories.

Now if you take the parent template  ```BirthsInCentury```'s Wikipedia page:

https://en.wikipedia.org/wiki/Template:Births_in_century

you can see that it has the following markup:

```
// ...

[[Category:{{Ordinal|{{#expr:{{{1|5}}}+1}}}} century|Births]]
[[Category:Births by year|#{{#ifexpr:{{{1|5}}}<9|0|}}{{#expr:{{{1|5}}}+1}}]]

// ...
```

containing the two remaining categories  ```Template:1st-century_births``` is inheriting from ```Template:Births_in_century```.

Now I saw the issue mentioned here:

http://dbpedia-discussion.narkive.com/WsDdFVsq/missing-links-among-categories

as well as in one of the GitHub issues of this repo #378 .

So I'm a little confused if this is now considered a bug, a missing improvement or a decision that was taken by the project not to crawl the inheritance tree ?

Also, are there other possibilities that would make it possible to access those categories like a work-around / pull request or is me forking the project my best shot at getting this feature ?

Thanks in advance! =D

**Comment by jimkont** [comment]
Hi @Mickael-van-der-Beek 
you are right in your observation that DBpedia currently does not expand templates to get categories or other data. 
This would need a full mw rendering engine to get it right but still it is not clear where the rendering should stop if we generalize this as the end result is html in most cases.

We can target specific information such as categories with different approaches. For now I can mark this as duplicate with issue #378.
