### ISSUE TITLE
Wrong type (i.e. xsd:integer) for properties stdinchi and inchi?

### ISSUE THREAD

**Issue by StefanSenger** [dbpedia/extraction-framework#409]
I found 4148 pages with the property stdinchi (http://dbpedia.org/property/stdinchi). For  4111 of the wikiPageIDs the value for the property stdinchi (http://dbpedia.org/property/stdinchi) was "1". For example: http://dbpedia.org/resource/Atorvastatin. Is it possible that the variable type is defined by the first character? The actual InChI (after "InChI=") starts with "1S" for a standard InChI. If the extraction workflow wrongly assigns xsd:integer this might explain why the InChI is truncated to just "1". 
For 37 cases the standard InChI wasn't "1" since the value started with "InChI=1S/".
The same is also true for the property inchi (http://dbpedia.org/property/inchi). Here the values start with "1/" and they are also truncated to just "1".

**Comment by jimkont** [comment]
data using the dbpedia.org/property namespace are meant to be dirty and provided only for completion.

To proper extract the properties you want you would have register on mappings.dbpedia.orgt and
 * update http://mappings.dbpedia.org/index.php/Mapping_en:Infobox_drug to also map the data you are interested in (i.e. stdinchi)
 * if the properties you need (i.e. stdinchi) are not yet defined inthe DBpedia ontology you can create them using the community process & tutorials defined in mappings.dbpedia.org
