### ISSUE TITLE
In data extracted from russian Wikipedia, lots of entries are misrepresented as books

### ISSUE THREAD

**Issue by mitya57** [dbpedia/extraction-framework#422]
If you look at the generated canonicalized datasets for russian Wikipedia (i.e. [this preview Turtle file](http://downloads.dbpedia.org/preview.php?file=2015-04_sl_core-i18n_sl_ru_sl_instance-types-en-uris_ru.ttl.bz2)), you will see that nearly half of the entries have their `rdf:type` set to `<http://dbpedia.org/ontology/Book>`.

For example:

    <http://dbpedia.org/resource/Baltic_Sea> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Book> .

Example from [localized dataset](
http://downloads.dbpedia.org/preview.php?file=2015-04_sl_core-i18n_sl_ru_sl_instance-types_ru.ttl.bz2):

    <http://ru.dbpedia.org/resource/Революция_1905—1907_годов_в_России> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Book> .

The relevant articles have the correct infoboxes set (i.e. {{Море…}} and {{революция…}} correspondingly). However, the extraction framework seems to ignore that and parse one of the references instead, which is a reference of the book. The properties of the created Book object are equal to references of that property (i.e. ISBN, etc).

This bug makes the Russian segment of DBpedia completely useless.

**Comment by jimkont** [comment]
if the book template is located first in the document then creates the main type.
this is a known limitation that we plan to fix in the next release (and probably add weights in the mappings).

since the mappings for the upcoming release are fixed, can you point us to the problematic infobox mappings and we will comment it out from the code.
You should also comment it out on the wiki and write a comment about the problem

**Comment by jimkont** [comment]
Looking at the [linked page](https://ru.wikipedia.org/wiki/Революция 1905—1907 годов в России)
the infobox 'революция' is not defined in the mappings wiki. The Russian DBpedia would be greatly improved if the Russian mapping community becomes more active
http://mappings.dbpedia.org/server/statistics/ru/

**Comment by mitya57** [comment]
Thanks for the links. I now see that lots of infoboxes are not mapped (approximately half of them).

It would still be nice if the articles with unsupported infoboxes would be treated as some generic type, not as a book. I.e. the [page you linked](http://mappings.dbpedia.org/server/statistics/ru/) says that "Book" is the most popular template which certainly should not be so.

**Comment by jimkont** [comment]
That page contains `{{Книга ...}}`  which is mapped to Book in the wiki
If `революция` has a mapping defined it would provide the main type for the resource and `Книга` would probably create a new intermediate resource describing the book

**Comment by mitya57** [comment]
OK, thanks for your response.
