### ISSUE TITLE
Broken link dbtax

### ISSUE THREAD

**Issue by pablomendes** [dbpedia/extraction-framework#423]
http://downloads.dbpedia.org/2015-04/core-i18n/en/instance_types_dbtax_ext_en.nt.bz2

**Comment by jimkont** [comment]
Thanks @pablomendes , where did you get that link?
http://downloads.dbpedia.org/2015-04/core-i18n/en/instance_types_dbtax_ext.nt.bz2 is the correct one

**Comment by praveenbalaji-blippar** [comment]
The link "Inferred Types DBTax (dbo)" on http://dbpedia.org/Downloads2015-04 is broken.

**Comment by jimkont** [comment]
fixed the link in the download page
