### ISSUE TITLE
A note on redirects

### ISSUE THREAD

**Issue by tgalery** [dbpedia/extraction-framework#425]
Hi there, I'm working on a project that uses both dbpedia and wikidata. To align the datasets I build a dbpedia/wiki title => wikidata id hashmap. When I manipulate data, I grab the wiki title and use the links in the `redirects.ttl` to grab the final link in the chain.
However, I'm still unable to match quite a few titles to wikidata ids. For example, I was unable to match Catriona_Le_May_Doan with a wikidata id. When I go wikipedia, though, Catriona_Le_May_Doan seems to redirect to Catriona_LeMay_Doan. If I grep for that title using the latest available dataset from http://wiki.dbpedia.org/Downloads2015-04,  I get this:

```
<http://dbpedia.org/resource/Catriona_LeMay> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
<http://dbpedia.org/resource/Catriona_Lemay_Doan> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
<http://dbpedia.org/resource/Catriona_LeMay-Doan> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
<http://dbpedia.org/resource/Catrina_Le-May_Doan> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
<http://dbpedia.org/resource/Catriona_LeMay_Doan> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
intruder@laptop:~/datasets/dbpedia/en$ bzcat ~/Downloads/transitive-redirects_en.ttl.bz2 | grep Catriona_Le_May_Doan
<http://dbpedia.org/resource/Catriona_LeMay> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
<http://dbpedia.org/resource/Catriona_Lemay_Doan> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
<http://dbpedia.org/resource/Catriona_LeMay-Doan> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
<http://dbpedia.org/resource/Catrina_Le-May_Doan> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
<http://dbpedia.org/resource/Catriona_LeMay_Doan> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Catriona_Le_May_Doan> .
```
This seems to indicate that calculation of the redirects works, but that http://dbpedia.org/resource/Catriona_Le_May_Doan should not appear as a final link in the chain. I wonder whether that is because the dataset is outdated or whether it is due to something in the extraction framework (or wikimedia markup). Also, what would be the difference between the `redirects` and the `transitive-redirects` file

**Comment by jimkont** [comment]
Sorry for the delayed response @tgalery 
`redirects.ttl` contain simple redirects like
```
titleA -> titleB
titleB -> titleC
titleC -> titleD
titleX -> titleY
```
in `transitive-redirects.ttl` we compute the transitive closure and have
```
titleA -> titleD
titleB -> titleD
titleC -> titleD
titleX -> titleY
```
One of the following things may have gone wrong (or we have a bug)
 * You get an intermediate redirect e.g. titleB
 * the wikidata link is newer that the DBpedia dump

**Comment by tgalery** [comment]
Hi dimitris, yeah I think it might be a case of the later. I will close this issue.
