### ISSUE TITLE
Mapping_zh.xml not working / property mapping not working

### ISSUE THREAD

**Issue by iampkuhz** [dbpedia/extraction-framework#427]
I'm try to extract Chinese triple from Chinese dump by using `Mapping_en.xml`(only changed the ns from 204 to 236)

Actually Chinese dump and English dump share some similliar Template, e.g. `infobox person`

however, after run extraction with 

    $ ../run extraction extraction.default.properties

while extraction.default.properties is as follows

    base-dir=downloadedDate/
    source=pages-articles.xml.bz2
    require-download-complete=false
    languages=10000
    extractors=.ArticleCategoriesExtractor,.ArticlePageExtractor,.ArticleTemplatesExtractor,.CategoryLabelExtractor,.ExternalLinksExtractor,.GeoExtractor,.InfoboxExtractor,.InterLanguageLinksExtractor,.LabelExtractor,.PageIdExtractor,.PageLinksExtractor,.RedirectExtractor,.RevisionIdExtractor,.ProvenanceExtractor,.SkosCategoriesExtractor,.WikiPageLengthExtractor,.WikiPageOutDegreeExtractor
    
    extractors.zh=.MappingExtractor
    ontology=../ontology.xml
    mappings=../mappings/
    
    uri-policy.iri=generic:en; xml-safe-predicates:*; reject-long:*
    format.ttl.bz2=turtle-triples;uri-policy.iri

I find the` infobox-properties-unredirecrt.ttl.bz2` in to output file, without the expected `infobox-properties-zh.ttl.bz2` file.

here is the whole output folder

    index.html
    zhwiki-20151201-article-categories.ttl.bz2
    zhwiki-20151201-article-templates.ttl.bz2
    zhwiki-20151201-category-labels.ttl.bz2
    zhwiki-20151201-external-links.ttl.bz2
    zhwiki-20151201-extraction-complete
    zhwiki-20151201-geo-coordinates-mappingbased.ttl.bz2
    zhwiki-20151201-geo-coordinates.ttl.bz2
    zhwiki-20151201-infobox-properties-unredirected.ttl.bz2
    zhwiki-20151201-infobox-property-definitions.ttl.bz2
    zhwiki-20151201-infobox-test.ttl.bz2
    zhwiki-20151201-instance-types-transitive.ttl.bz2
    zhwiki-20151201-instance-types.ttl.bz2
    zhwiki-20151201-interlanguage-links.ttl.bz2
    zhwiki-20151201-labels.ttl.bz2
    zhwiki-20151201-mappingbased-literals.ttl.bz2
    zhwiki-20151201-mappingbased-objects-uncleaned-unredirected.ttl.bz2
    zhwiki-20151201-out-degree.ttl.bz2
    zhwiki-20151201-page-ids.ttl.bz2
    zhwiki-20151201-page-length.ttl.bz2
    zhwiki-20151201-page-links-unredirected.ttl.bz2
    zhwiki-20151201-pages-articles.xml.bz2 # the original file
    zhwiki-20151201-redirects.ttl.bz2
    zhwiki-20151201-revision-ids.ttl.bz2
    zhwiki-20151201-revision-uris.ttl.bz2
    zhwiki-20151201-skos-categories.ttl.bz2
    zhwiki-20151201-specific-mappingbased-properties.ttl.bz2
    zhwiki-20151201-template-redirects.obj
    zhwiki-20151201-wikipedia-links.ttl.bz2
    

Is there ant config error or how can i export the triple with converted property by mapping.xml?

thanks a lot !

**Comment by jimkont** [comment]
interesting hack ;)
the `infobox-properties-unredirecrt.ttl.bz2` comes from the (raw) infobox extractor, not the mappings extractor

The mappings extractor creates the following two dumps
```
zhwiki-20151201-mappingbased-literals.ttl.bz2
zhwiki-20151201-mappingbased-objects-uncleaned-unredirected.ttl.bz2
```
so if your hack  works, you should find the triples here

**Comment by iampkuhz** [comment]
thanks a lot!
