### ISSUE TITLE
Problem with http://dbpedia.org/resource/Cannabis_(drug)

### ISSUE THREAD

**Issue by Hronom** [dbpedia/extraction-framework#432]
Hello everyone!

I use dumps from http://downloads.dbpedia.org/2015-04/core-i18n/

So at dumps `instance-types-en-uris_de.nt` I have next triple:
```
instance-types-en-uris_de.nt(457385): <http://dbpedia.org/resource/Cannabis_(drug)> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Quote> .
```
Looks like type `http://dbpedia.org/ontology/Quote` is wrong for `http://dbpedia.org/resource/Cannabis_(drug)`.

I check version of this dumps in http://downloads.dbpedia.org/2015-10/core-i18n/ and http://downloads.dbpedia.org/current/core-i18n/ and they also contains this error.

Please can you check this...

**Comment by jimkont** [comment]
similar to #434 this is probably due to a wrong mapping that is now deleted, as there are no (German) mappings to the class `Quote`

http://mappings.dbpedia.org/index.php?title=Special%3AWhatLinksHere&target=OntologyClass%3AQuote&namespace=

so I close this as no action needs to be taken
