### ISSUE TITLE
Problem with http://dbpedia.org/resource/Blade_&_Soul

### ISSUE THREAD

**Issue by Hronom** [dbpedia/extraction-framework#434]
Hello,

I use dumps from http://downloads.dbpedia.org/2015-04/core-i18n/

So at dump `instance-types-en-uris_pt.nt` I have next triple:
```
instance-types-en-uris_pt.nt(229328): <http://dbpedia.org/resource/Blade_&_Soul> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/TelevisionShow> .
```
Looks like type `http://dbpedia.org/ontology/TelevisionShow` is wrong for `http://dbpedia.org/resource/Blade_&_Soul`.

Please can you check this...

**Comment by jimkont** [comment]
Looking here
http://mappings.dbpedia.org/index.php?title=Special%3AWhatLinksHere&target=OntologyClass%3ATelevisionShow&namespace=218

I see that template mapping: http://mappings.dbpedia.org/index.php/Mapping_pt:Info/Animang%C3%A1/Anime

should be probably mapped to `Anime` and not `TelevisionShow`

@Hronom would you care to change this mapping?

**Comment by Hronom** [comment]
@jimkont Yes, I can, but... it's take many time because I don't know how mappings works, and what I need to do, this is why I write here.

**Comment by jimkont** [comment]
it is quite easy to write / edit a mapping but any contribution is welcome
so if you can get us other related type errors, we will make sure the related mappings are fixed

Thanks again @Hronom !
