### ISSUE TITLE
Problem with http://dbpedia.org/resource/Encoder

### ISSUE THREAD

**Issue by Hronom** [dbpedia/extraction-framework#438]
Hello,

I use dumps from http://downloads.dbpedia.org/2015-04/core-i18n/

So http://dbpedia.org/resource/Encoder has `rdf:type` http://dbpedia.org/ontology/MusicGenre and http://www.wikidata.org/entity/Q188451 but on https://en.wikipedia.org/wiki/Encoder I didnt find any hints about MusicGenre type...

Please can you check this...

**Comment by jimkont** [comment]
I think this type comes from the SD-Types provided by @HeikoPaulheim and is duplicate of #241, #414, #445
