### ISSUE TITLE
http://dbpedia.org/page/%7B%7B

### ISSUE THREAD

**Issue by johnSerrano** [dbpedia/extraction-framework#441]
This is either a glitch or the most interesting thing in the world. According to the database, "{{" is a country, The currency of the United States, the developer of Blender, discoverer of Uranus, birthplace of Torvalds, and builder of the Titanic. A whole lot of disparate nodes seem to point here.

**Comment by jimkont** [comment]
Thanks @johnSerrano  for the report, this issue is now fixed #406 but data will change in the following release
