### ISSUE TITLE
dbpedia extraction errors for links within texts

### ISSUE THREAD

**Issue by xiliang** [dbpedia/extraction-framework#48]
When the wikipedia value contains texts with links in it, dbpedia
turns to extract the first wiki link.
One example below, "Barack Obama" becomes a occupation for "Stephanie
Cutter" since [[Barack Obama]] appears in the text of occupation.

```
http://en.wikipedia.org/wiki/Stephanie_Cutter     Occupation    Deputy campaign manager for President [[Barack Obama]]'s 2012 reelection campaign.
```

```
http://live.dbpedia.org/page/Stephanie_Cutter    dbpedia-owl:occupation    dbpedia:Barack_Obama
```

This seems a general extraction errors and also exists for other wiki pages.
Two more examples:

1. Britney_Spears extracted as notable work instead of her song
http://en.wikipedia.org/wiki/Sheppard_Solomon
* [[Britney Spears]] - "[[Touch of My Hand]]"

http://live.dbpedia.org/page/Sheppard_Solomon
dbpedia-owl:notableWork         dbpedia:Britney_Spears

2. Adolf_Hitler extracted an occupation
http://en.wikipedia.org/w/index.php?title=Johann_Baur&action=edit
laterwork     =Became [[Adolf Hitler]]'s personal pilot

http://live.dbpedia.org/page/Johann_Baur
dbpedia-owl:occupation          dbpedia:Adolf_Hitler

**Comment by jimkont** [comment]
This is now solved with https://github.com/dbpedia/extraction-framework/blob/master/scripts/src/main/scala/org/dbpedia/extraction/scripts/TypeConsistencyCheck.scala as a post processing step
