### ISSUE TITLE
unnamed (positional) parameters not recognized

### ISSUE THREAD

**Issue by chrysn** [dbpedia/extraction-framework#483]
few resources have their imdbId extracted ([IMDb title template extractor](http://mappings.dbpedia.org/index.php/Mapping_en:IMDb_title); <10% in my test sample), even though coverage of imdb links in wikipedia is great (>90%). it appears that the extraction only works when the template is used with named arguments (eg. `{{IMDb title|id=0118583}}` in https://en.wikipedia.org/wiki/Alien:_Resurrection), not when they are used positionally (eg. `{{IMDb title|0103644|Alien 3}}` in https://en.wikipedia.org/wiki/Alien_3). the unnamed form is listed first on the [imdb template description](https://en.wikipedia.org/wiki/Template:IMDb_title).

i didn't find any info on how to add support for unnamed (positional?) template arguments to an extractor, so it seems to me that's not possible. if yes, please add support for that; if not, please point me to where i can find information on how to fix the extractor.

**Comment by chile12** [comment]
This is a mapping issue. 
It wold be of great help, if you could update the mappings for movies to cover all possible occurrences of the imdb id. The updated ids would then show up with the next release.

**Comment by chrysn** [comment]
on the [property mapping description](http://mappings.dbpedia.org/index.php/How_to_edit_DBpedia_Mappings#Property_Mapping), i found how to set which named argument (`templateProperty=id`) is which ontology predicte (`ontologyProperty=imdbId`), but it makes no reference to where i could put the information that it's the first argument when no property name is used (i'd be looking for something like `templateArgumentIndex=1`).

how would i specify that the first unnamed argument to the imdb title mapping is also imdbId? i did not find that in the mapping wiki.

**Comment by chile12** [comment]
is this not covered by select (third bullet point)
so in your case:
select=first ?
I'm not an active mapper, so not the best candidate for in depth mapping questions.

**Comment by chrysn** [comment]
the select=first looks more of an "if there are multiple values for this, use the nth". the [current users of it](http://mappings.dbpedia.org/index.php/Mapping_de:Infobox_Software) are not completely conclusive on this, because what is used there with select= would typically only occur once anyway, but the presence of two select=first on [a french mapping](http://mappings.dbpedia.org/index.php/Mapping_fr:Infobox_Musique_(artiste)) indicates that it does not have the meaning you suggested.

**Comment by chile12** [comment]
true, well I had a look at the example.
I don't think the current mapping regime can cope with that (please correct me on that if I'm wrong).
That said, we are in the process of switching the whole mappings to an [RML](http://rml.io) & Git based approach. With RML you can most certainly extract those values.

**Comment by chile12** [comment]
Also, we have a separate issue tracker for mappings:
https://github.com/dbpedia/mappings-tracker/issues
if you want to ask the mapping community directly.
