### ISSUE TITLE
Missing English abstracts and comments

### ISSUE THREAD

**Issue by mzarozinski** [dbpedia/extraction-framework#486]
It appears as if the new release (version 2016-04) is missing some English abstract and comment fields.

For example, last week I was able to get the abstract for George Washington, now there are eight abstracts but none are in English.

sparql query:

```
SELECT ?abstract
  WHERE { 
    <http://dbpedia.org/resource/George_Washington> dbo:abstract ?abstract .
    FILTER langMatches( lang(?abstract), "en" )
  }
```

[query results](http://dbpedia.org/snorql/?query=%20%20%20%20SELECT%20%3Fabstract%0D%0A%20%20%20%20WHERE%20%7B%20%0D%0A%20%20%20%20%20%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FGeorge_Washington%3E%20dbo%3Aabstract%20%3Fabstract%20.%0D%0A%20%20%20%20%20%20FILTER%20langMatches%28%20lang%28%3Fabstract%29%2C%20%22en%22%20%29%0D%0A%20%20%20%20%7D)

Has that data moved somewhere else or is it missing in this release?

**Comment by openlink** [comment]
I have alerted the developers who create the dumps to check what is going on.

I checked the dump files loaded into http://dbpedia.org/sparql and they do not contain an english abstract for <http://dbpedia.org/resource/George_Washington>

**Comment by openlink** [comment]
I restored missing abstracts and comments with data from the 2015-10 dataset.
Example:
   http://dbpedia.org/resource/George_Washington

Once the DBpedia team (cc @jimkont) have a formal new datadump for the long_abstracts_en.ttl.bz2 and short_abstracts_en.ttl.bz2 i will update the official dbpedia endpoint with it.

**Comment by chile12** [comment]
Thanks Patrick,
concerning the missing and erroneous abstracts of the last release:
We are going to provide a hot-fix, changing out all abstracts for the 2016-04 release.
We encountered an issue with the wikipedia/wikimedia sql import not showing up in the log files, which we did not recognize in time.
Coming up in one or two weeks.
