### ISSUE TITLE
"Interlanguage Links"dataset decompression failure

### ISSUE THREAD

**Issue by johnlevi** [dbpedia/extraction-framework#493]
Hi all,
All ttl tql format dataset(en,zh,ko,ja) of row "Interlanguage Links" in the following url page can not be decompressed successfully: http://wiki.dbpedia.org/downloads-2016-04#datasets

Would anyone recheck it or fix it?
Thanks a lot!

**Comment by chile12** [comment]
Hi there, 

I tested:
interlanguage_links_zh.ttl.bz2
interlanguage_links_ja.ttl.bz2
interlanguage_links_ko.ttl.bz2

all are fine.
Please make sure you download was no interrupted. Also compare with md5 values provided for each file.

Best
