### ISSUE TITLE
Extracted category hierarchy does not reflect wikipedia content

### ISSUE THREAD

**Issue by bm371613** [dbpedia/extraction-framework#498]
According to dbpedia's `<http://www.w3.org/2004/02/skos/core#broader>` relation, `<http://dbpedia.org/resource/Category:Sociological_terminology>` has the following children:
```
http://dbpedia.org/resource/Category:Dialect_levelling
http://dbpedia.org/resource/Category:Environmental_social_science_concepts
http://dbpedia.org/resource/Category:Globalization_terminology
http://dbpedia.org/resource/Category:Imperialism_terminology
http://dbpedia.org/resource/Category:Modernity
http://dbpedia.org/resource/Category:Social_groups
http://dbpedia.org/resource/Category:Social_systems
http://dbpedia.org/resource/Category:Western_culture
http://dbpedia.org/resource/Category:Ideologies
http://dbpedia.org/resource/Category:Autism_rights_movement
```

Looking at `https://en.wikipedia.org/wiki/Category:Sociological_terminology` (all revisions), it should be
```
http://dbpedia.org/resource/Category:Dialect_levelling
http://dbpedia.org/resource/Category:Globalization_terminology
http://dbpedia.org/resource/Category:Western_culture
```

**Comment by jimkont** [comment]
Hi @bm371613 

`skos:broader` triples are different from  `is skos:broader of` triples.
Also note that the pages you mention at the end are sub-categories and not super-categories (broader).
https://en.wikipedia.org/w/index.php?title=Category:Sociological_terminology&action=edit&oldid=641359320

if you go at the end of the resource page and look at the  `is skos:broader of` you will find the categories you expect, along with a few other.

let me know if you have any more questions or feel free to close the issue

**Comment by bm371613** [comment]
The issue is the "along with few other" part. Why is "Ideologies" among these few others? I expected the "is skos:broader of" section to contain the exact same three items I see as subcategories on wikipedia.

**Comment by jimkont** [comment]
because at extraction time, "Ideologies" had `Sociological_terminology` as parent category
https://en.wikipedia.org/w/index.php?title=Category:Ideologies&action=edit&oldid=689633981

**Comment by jimkont** [comment]
you can track the wikipedia revision uri from `prov:wasDerivedFrom` triples

**Comment by bm371613** [comment]
Thanks for pointing this out! I did check subcategories sections of all old revisions of `Sociological_terminology` looking for `Ideologies`, but I suppose that always shows the current subcategories, using the current database to replace subcategories directive.
