### ISSUE TITLE
unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by ho9science** [dbpedia/extraction-framework#501]
I have a problem

I want download wiki dump data for extraction

![image](https://cloud.githubusercontent.com/assets/13064046/24645990/2fb7bb56-1955-11e7-979a-72f2cfd071c2.png)

- bellow is error message
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to a requested target

I did add the certificate my JVM. (it's java8)

please help me

**Comment by kurzum** [comment]
unable to reprodue and quite old
