### ISSUE TITLE
error when downloading dumps cause of config file (mac OS X )

### ISSUE THREAD

**Issue by AlexandraHofmann** [dbpedia/extraction-framework#503]
When executing the command `mvn scala:run "-Dlauncher=download"   "-DaddArgs=config=download.minimal.properties"` to download dumps, the dump extraction fails using Mac OS X Sierra (Version 10.12.4).

This is the config file with the changed directory (which exists!) and a language which is defined in the mapping:
![bildschirmfoto 2017-04-23 um 17 13 14](https://cloud.githubusercontent.com/assets/15103985/25314633/34c401a2-2848-11e7-8f0a-cc4ae19722e5.png)

This is the error which appears in the console. Same error comes up with root privileges.
![bildschirmfoto 2017-04-23 um 17 02 02](https://cloud.githubusercontent.com/assets/15103985/25314583/529cfec8-2847-11e7-81f3-7610628ac4d5.png)

**Comment by AlexandraHofmann** [comment]
issue solved.

**Comment by krishh-konar** [comment]
@AlexandraHofmann can you expalin what you did to solve this issue?

**Comment by AlexandraHofmann** [comment]
@krishh-konar Actually it was just misleading in the description.
There is no issue with mac. It was just an error because the description did not mention that the mvn command has to be executed within the dump folder of the application. This solved the issue.
