### ISSUE TITLE
 Have issues about "zh.dbpedia.org"

### ISSUE THREAD

**Issue by GeorgieJi** [dbpedia/extraction-framework#506]
I recently tried to use dbpedia to build a knowledge mapping, but when I attempted to open urls, like "http://zh.dbpedia.org/resource/黄幻吾", I found that all the websites related to "zh.dbpedia" have no access to enter. Is it possible for you to give a hand to solve it? Sincerely thanks for your help and responses.

**Comment by chile12** [comment]
This would be the task of the Chinese DBpedia chapter (which is not existing yet I think).
The DBpedia Association only provides web access to the English entities (as it is by far the largest language dataset) with some alternative labels and abstracts (also in zh). Please feel free to organize and create the Chinise Chapter if you are interested. If you want to know what a chapter does I can point you to: http://wiki.dbpedia.org/about/language-chapters.
