### ISSUE TITLE
rml:source refers to wikipedia, should be to mapping wiki

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#507]
@wmaroy This RML mapping https://github.com/dbpedia/extraction-framework/blob/rml/mappings/rml/en/Mapping_en:DavisCup_player.ttl
has rml:source                "http://en.wikipedia.org/wiki/Mapping_en:DavisCup_player?oldid=28857"
but should be  http://mappings.dbpedia.org/index.php?title=Mapping_en:DavisCup_player&oldid=28857

**Comment by wmaroy** [comment]
It should actually refer to the wiki page where the Infobox that is being extracted. Fixed in https://github.com/dbpedia/mappings-tracker/commit/eb772f034576672bf39210406fe225d9bf659dd9.
