### ISSUE TITLE
Download issue - no language was define

### ISSUE THREAD

**Issue by NirMendel** [dbpedia/extraction-framework#509]
Hey, 
I'm trying to do a basic dump download (for future extraction), and in the meantime things don't go as smoothly as I hope.
I have the latest master branch.
I'm using maven 3.3.9, and Java version 1.8.0, on Ubuntu 16.
The first issue was, when I tried to run:
../run download config=download.minimal.properties
it threw an exception of 'FileNotFound'

once I removed the 'config=', and just ran:
../run download download.minimal.properties
it tried to read my configuration file (this was an alert for me that I may do something wrong).

I tried to continue , and modified download.minimal.property with:
base-url=http://dumps.wikimedia.org/
base-dir=/home/mcmendel/DBPedia/dumps
download=en:pages-articles\d+.xml.bz2
unzip=true
retry-max=5
retry-millis=10000

and  the next excepttion I receive is:
No files to doenload, because no languages were defined.

What could be the problem?
Thanks

**Comment by chile12** [comment]
Hi there, I updated the Download script.
This is the template of a properties file to use from now on out:
https://github.com/dbpedia/extraction-framework/blob/master/dump/download.10000.properties

As you can see the downloads property is gone and replaces by [languages](https://github.com/dbpedia/extraction-framework/blob/master/dump/download.10000.properties#L9) and [resource](https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/resources/universal.properties#L48)

Also please make sure to edit the universal.properties file in core and and install afterwards.
When starting a new extraction, you should first edit this document, base-dir and source are specified there. While you can override all properties in the task-specific properties file, it will prevent u from re-entering common properties anew.

**Comment by NirMendel** [comment]
@chile12
it works now, thanks!
