### ISSUE TITLE
international RML mappings: encoding issues

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#511]
@wmaroy 
- https://github.com/dbpedia/extraction-framework/tree/rml/mappings/rml/bg: the file names are unreadable.
- take one of them https://github.com/dbpedia/extraction-framework/blob/rml/mappings/rml/bg/Mapping_bg:╨Р╨║╤В╤М╨╛╤А.ttl
```ttl
@base	          	<http://bg.dbpedia.org/resource/Mapping_bg:Актьор/> .

<http://bg.dbpedia.org/resource/Mapping_bg:%D0%90%D0%BA%D1%82%D1%8C%D0%BE%D1%80>
  a                      rr:TriplesMap ;
  rml:logicalSource      <http://bg.dbpedia.org/resource/Mapping_bg:%D0%90%D0%BA%D1%82%D1%8C%D0%BE%D1%80/LogicalSource> ;
```
`@base` uses IRI but the rest of the file uses ugly encoded URLs. Please use unicode IRIs throughout

**Comment by wmaroy** [comment]
The RML mappings are updated with IRIs throughout now, the mappings are stored here now:
https://github.com/dbpedia/mappings-tracker

**Comment by VladimirAlexiev** [comment]
https://github.com/dbpedia/mappings-tracker/blob/master/mappings/bg/Mapping_bg:Автомобил.ttl looks great and https://github.com/dbpedia/extraction-framework/blob/rml/mappings/rml/bg/ is deleted. Thanks!
