### ISSUE TITLE
occupation handled differently (dbo:occupation IntermediateNode vs dbp:occupation)

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#513]
Occupation info about [dbr:Michael_Jackson](http://dbpedia.org/page/Michael_Jackson) and [dbr:Mariah_Carey](http://dbpedia.org/page/Mariah_Carey) is output very differently:
```ttl
dbr:Mariah_Carey dbo:occupation	dbr:Mariah_Carey__1.
dbr:Mariah_Carey__1 a dbo:PersonFunction, owl:Thing;
  dbo:title "Singer", songwriter", actress", "record producer".

dbr:Michael_Jackson
 dbp:occupation "Singer", "record producer", "songwriter", "actor", "dancer", "businessman", "philanthropist".
```
- one has dbp:occupation, the other has dbo:occupation.
  @jimkont, @kurzum: if the presence of `dbo:` suppresses the emission of `dbp:` that is a nbig mistake!
- one has IntermediateNode `dbo:PersonFunction` (quite useless in this case), the other has direct literals
This spuruous difference makes querying for that info very hard.

The source of the two pages is the same:
- [Mariah_Carey](https://en.wikipedia.org/w/index.php?title=Mariah_Carey&action=edit&oldid=745146468&editintro=Template:BLP_editintro):
```
{{Infobox person
| occupation          = {{hlist|Singer|songwriter|actress|record producer}}
```
- [Michael_Jackson](https://en.wikipedia.org/w/index.php?title=Michael_Jackson&action=edit&oldid=745329258)
```
{{Infobox person ii
| occupation      = <!--Please do not add any more occupations to the list, it is long enough already-->
  {{hlist|Singer|songwriter|dancer|actor|record producer|businessman|philanthropist}}
```
([Infobox_person_ii](https://en.wikipedia.org/w/index.php?title=Template:Infobox_person_ii&redirect=no) redirects to Infobox_person)

So where does the difference come from?

**Comment by mgns** [comment]
The problem with occupation seems to be fixed (with the next release): http://mappings.dbpedia.org/server/extraction/en/extract?title=Michael+Jackson&revid=&format=trix&extractors=mappings
