### ISSUE TITLE
BAD URI in anchor text dataset

### ISSUE THREAD

**Issue by hamidzafar** [dbpedia/extraction-framework#517]
I have been checking out the anchor text (http://downloads.dbpedia.org/2016-04/core-i18n/en/anchor_text_en.ttl.bz2) data and I notice that there are a few malformed URIs like:

`# <BAD URI: Illegal character in path at index 47: http://en.dbpedia.org/resource/Prince_of_Orange > <http://dbpedia.org/ontology/wikiPageWikiLinkText> "Prince of Orange "@en .`
or
`# <BAD URI: length 771 exceeds maximum 500: http://en.dbpedia.org/resource/%3C/nowiki%3E(4''S'')-1-%5B2-%5B2-%3Cnowiki%3E%5B%5B%3C/nowiki%3E2-%3Cnowiki%3E%5B%5B%3C/nowiki%3E2-%3Cnowiki%3E%5B%5B%3C/nowiki%3E(2''R'')-2-%3Cnowiki%3E%5B%5B%3C/nowiki%3E2-%5B2-%5B2-%5B(2-acetamido-3-phenylpropanoyl)-methylamino%5Dpropanoyl-methylamino%5Dpropanoyl-methylamino%5Dacetyl%5Damino%5D-2-methylbutanoyl%5Damino%5Dacetyl%5Damino%5D-4-methylpentanoyl%5D-methylamino%5Dpropanoyl-methylamino%5Dacetyl%5D-4-hydroxypyrrolidine-2-carbonyl%5Damino%5D-''N''-%5B(2''R'')-1-%5B(4''S'')-4-hydroxy-2-%3Cnowiki%3E%5B%5B%3C/nowiki%3E1-%5B2-%3Cnowiki%3E%5B%5B%3C/nowiki%3E(2''S'')-1-hydroxy-3-phenylpropan-2-yl%5Dcarbamoyl%5Dpyrrolidin-1-yl%5D-1-oxopropan-2-yl%5D-methylcarbamoyl%5Dpyrrolidin-1-yl%5D-2-methyl-1-oxobutan-2-yl%5Dpentanediamide> <http://dbpedia.org/ontology/wikiPageWikiLinkText> "</nowiki>(4''S'')-1-[2-[2-<nowiki>[[</nowiki>2-<nowiki>[[</nowiki>2-<nowiki>[[</nowiki>(2''R'')-2-<nowiki>[[</nowiki>2-[2-[2-[(2-acetamido-3-phenylpropanoyl)-methylamino]propanoyl-methylamino]propanoyl-methylamino]acetyl]amino]-2-methylbutanoyl]amino]acetyl]amino]-4-methylpentanoyl]-methylamino]propanoyl-methylamino]acetyl]-4-hydroxypyrrolidine-2-carbonyl]amino]-''N''-[(2''R'')-1-[(4''S'')-4-hydroxy-2-<nowiki>[[</nowiki>1-[2-<nowiki>[[</nowiki>(2''S'')-1-hydroxy-3-phenylpropan-2-yl]carbamoyl]pyrrolidin-1-yl]-1-oxopropan-2-yl]-methylcarbamoyl]pyrrolidin-1-yl]-2-methyl-1-oxobutan-2-yl]pentanediamide"@en .`

Here is a complete list of the line numbers that has the similar problem:
`[339934, 432838, 1632347, 3463161, 10406242, 13886220, 15382148, 15414928, 15414931, 15414935, 15414937, 16446371, 18327920, 18327921, 18327922, 21739021, 22760207, 22781603, 22872159, 24899871, 26379247, 28865978, 30993977, 31665700, 36280611, 36750926, 37022811, 37878408, 37955396, 38202813, 39080204, 45945599, 46087376, 47082521, 48718396, 49170168, 49170300, 50481527, 55494226, 59027006, 64119097, 70298838, 71471387, 73876496, 79243719, 80228870, 81545282, 82089773, 82089776, 84715943, 86533340, 87351246, 87956069, 88379029, 88728788, 89548585, 89548591, 96120108, 96122200, 101176163, 103062533, 105875616, 105875619, 107045885, 110528632, 112772723, 114143099, 114720148, 116427306, 116804410, 117949978, 120930627, 121446617, 122012240, 122012751, 125643979, 125643980, 125643982, 125930014, 126137883, 126936472, 126937069, 126944493, 126944797, 126944855, 126945018, 126945077, 126945501, 126945579, 126945890, 126946602, 126946686, 126946818, 126946910, 126947788, 126957182, 126957364, 126957498, 126957552, 126957616, 126957783, 126957990, 126958217, 127943368, 127943892, 127944158, 127944240, 127945896, 127946178, 127946546, 127947803, 127950514, 127951871, 127952115, 127953136, 127953451, 127954188, 127954337, 127954482, 127954535, 127954578, 127955035, 127955141, 127955233, 127955827, 127956514, 127957071, 127957339, 127957439, 127957926, 127958011, 127958258, 127958298, 127958371, 127958479, 127958662, 127958871, 127959193, 127959242, 127959519, 127966966, 127967153, 127967197, 127967237, 128256368, 128258126, 128258175, 129474632, 130642568, 130897014, 130900614, 130900675, 130900678, 130903367, 130905252, 130905494, 131062228, 131062229, 131062230, 131062231, 131062232, 131062257, 131062287, 131062293, 131062296, 136939212, 138684936, 138772016, 139434542, 139434606, 139572282, 139572293, 139572295, 139889840, 140899603, 141494146, 143873855, 144809486, 145859489, 147145221, 149150729, 149296695, 149296698, 149296699, 149296706, 149861896, 150322591, 151022295, 151478647, 151478649, 151478650, 151478651, 151478652, 151478653, 151478654, 151478655, 151478656, 151478657, 151478658, 151478659, 151478660, 151498216, 151498217, 151879721, 151879726, 151879727, 151879728, 151879729, 151879736, 151879737, 151879739, 151879740, 151879742, 151879749, 151879750, 151879757, 151879767, 151879769, 151879770, 151963972, 152414907, 152993253, 153313382, 154768576, 155537348, 156468394, 156560557, 156624727, 156624729, 156651408, 156651412, 156651414, 156651416, 156651417, 156651424, 156651426, 156651430, 156651432, 156744625, 156744626, 156744627, 156744628, 156804802]`

I hope this the right place to report such errors, otherwise let me know where I can post them.

**Comment by chile12** [comment]
Thanks for making us aware, I will look into this..

I would suggest using the nif_text_links datasets instead of the anchor texts. It captures all text links including the anchor texts. See here: http://wiki.dbpedia.org/nif-abstract-datasets.

**Comment by hamidzafar** [comment]
@chile12 Thanks for your reply and the pointer to the other dataset.

**Comment by jimkont** [comment]
Sometimes the wiki text extraction fails (most times due to wrong syntax by
the Wikipedia editors) and we get to serialize a value to an IRI the gets
huge and with strange characters.

One option would be to skip these triples when they are produced but there
are many places where this may happen and would result in a lot of code
duplication. The decision was to catch them during serialization as it is
the final sink of all generated triples.

There were two options for these triples, either skip them or write them as
comments in case they can be somehow fed back to DBpedia / Wikipedia. The
latter was chosen and this is why you see them.
Any n triples parser would ignore them and they do no harm sitting there.
Would be nice if someone could pick them up and find a way to use them for
fixing the error source.

**Comment by hamidzafar** [comment]
@jimkont Thanks for pointing out the reason we saw such flaws in the source of data.

**Comment by chile12** [comment]
I will close
