### ISSUE TITLE
update NYTimes semantic URLs

### ISSUE THREAD

**Issue by VladimirAlexiev** [dbpedia/extraction-framework#521]
http://dbpedia.org/page/3M says that `nyt:3M` is 
http://data.nytimes.com/N38115567920937854392.
However, that is long obsolete and doesn't resolve.

If you go to https://tools.wmflabs.org/sqid/#/browse?type=properties 
and do "filter labels" by "new york" or "nyt", you'll see 5 new URL patterns that work.
- Eg for "New York Times Semantic Concept: Organization": 
http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_org/3M%20Company.json?fields=all&api-key=
- The odd one amongst these 5 is "NYT topic ID":
https://www.wikidata.org/wiki/Property:P3221

(Note:  I wrote this in some notes Dec 2016, so don't remember what is "odd" about P3221, and have no clue how to go from `N38115567920937854392` to `nytd_org/3M Company`)

**Comment by chile12** [comment]
transferred to dbpedia/links: https://github.com/dbpedia/links/issues/40
