### ISSUE TITLE
[DBpedia NIF] URLs do not correspond to NIF 2.1

### ISSUE THREAD

**Issue by m1ci** [dbpedia/extraction-framework#533]
In the DBpedia NIF dataset (2016-10) update the URLs according to the NIF 2.1, e.g. `char=0,334` should be `offset_0_334`

Also, all contexts, words, phrases, sections and paragraphs should be typed with ``nif:OffsetBasedString``

\cc @kurzum

**Comment by chile12** [comment]
The URL format was prescribed by @kurzum
