### ISSUE TITLE
[DBpedia NIF] merge the three NIF partitions

### ISSUE THREAD

**Issue by m1ci** [dbpedia/extraction-framework#534]
According to the feedback from the community, we would need to merge the three NIF partitions (``nif_context_en.ttl.bz2, nif_page_structure_en.ttl.bz2, nif_text_links_en.ttl.bz2``) into one.

**Comment by chile12** [comment]
I dont like this idea, I would rather advise to read them in parallel if you are interested in retrieving the complete set of triples for a given page.

**Comment by m1ci** [comment]
Keeping these separated probably makes sense.
