### ISSUE TITLE
Malformed rdf/xml serialization

### ISSUE THREAD

**Issue by mainka** [dbpedia/extraction-framework#540]
Query:
`
$ curl -LH "Accept: application/rdf+xml" http://fr.dbpedia.org/resource/Seconde_Guerre_mondiale
`

The generated serialization is not well-formed. Line 79,557 reads:
`
<prop-fr:faitsD’armes rdf:resource="http://fr.dbpedia.org/resource/Seconde_Guerre_mondiale" />
`
`faitsD’armes` is not a valid xml Name, because `'’'` (`\u2019`) (`RIGHT SINGLE QUOTATION MARK`) is not a valid xml NameChar.

**Comment by LorenzBuehmann** [comment]
That's a known Virtuoso bug. I already reported two related issue some time ago

**Comment by JJ-Author** [comment]
since this has nothing to do with the extraction framework i close this issue but marked for reference with endpoint tag

a valid rdf/xml output would look like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:ns0="http://fr.dbpedia.org/property/faitsD'"
         xmlns:ns1="http://dbpedia.org/ontology/"
         xmlns:ns2="http://fr.dbpedia.org/prop/">

  <rdf:Description rdf:about="http://fr.dbpedia.org/resource/Richard_John">
    <ns0:armes rdf:resource="http://fr.dbpedia.org/resource/Seconde_Guerre_mondiale"/>
    <ns1:conflict rdf:resource="http://fr.dbpedia.org/resource/Seconde_Guerre_mondiale"/>
    <ns1:wikiPageWikiLink rdf:resource="http://fr.dbpedia.org/resource/Seconde_Guerre_mondiale"/>
    <ns2:conflit rdf:resource="http://fr.dbpedia.org/resource/Seconde_Guerre_mondiale"/>
  </rdf:Description>

</rdf:RDF>
```
