### ISSUE TITLE
Wrong usage of equivalence relation in class hierarchy

### ISSUE THREAD

**Issue by LorenzBuehmann** [dbpedia/extraction-framework#541]
I don't know who did it and why but in the current ontology the following axiom exists:

```
Class: dbo:MusicGenre
    EquivalentTo: dul:Concept
```
This doesn't make any sense and in addition brings a lots of problems into the ontology as there are even other classes made equivalent to `dul:Concept` - you know what this means for the transitive closure...

Now, when I opened the ontology in Protege, I saw that there are much more issues suffering from the same problems. For sure, somebody misunderstood the semantics of the equivalence relation.

I'll just add a screenshot of the Protege class hierarchy here for convenience. Please check all the weird equivalence relations even on this small part of the class hierarchy. (note, the list of red markers is probably incomplete, I just stopped after tagging just some the obvious issues in this part of the hierarchy:

![bug](https://user-images.githubusercontent.com/976029/35450508-8ce7d130-02c0-11e8-9937-6a9f1e0f81e7.png)

For example:
* `dbo:Aircraft` should not have been made equivalent to `schema:Concept`, the same for `dbo:Locomotive`,  `dbo:Ship` etc - this indeed makes all entities equivalent entities.
* something like `dbo:Food owl:equivalentClass dbo:FunctionalSubstance` is not what I would assume to be correct
* Polyhedron a SpaceRegion and vice versa? No

Another example regarding the union classes of Schema.org:
```
dbo:College owl:equivalentClass schema:CollegeOrUniversity .
dbo:University owl:equivalentClass schema:CollegeOrUniversity .
```
This is also wrong and occurs several times - the keyword is "Or" - the axioms above result in 
```
dbo:College owl:equivalentClass dbo:University
```
which is clearly unintended.

Mostly, the `owl:equivalentClass` relations to the external vocabularies DUL and Schema.org are the root cause.

For me, this looks like a larger problem within the current ontology, especially as this makes all applications using reasoning behave strange and sometimes even useless.

**Comment by mgns** [comment]
I removed a number of problematic equivalence relationships. Now there are no inconsistent classes in the ontology itself. Disclaimer: when loading the ontology with DBpedia instance data, there may occur inconsistencies, in particular because of domain, range and disjoint class restrictions.
