### ISSUE TITLE
Extraction error after finish

### ISSUE THREAD

**Issue by onlyjiny** [dbpedia/extraction-framework#545]
Hi.

I have been trying to use the extraction-framework for extracting knowledge from ko Wikipedia.
For my job, I have used only MappingExtractor like below.

> ...
> extractors=
> extractors.ko=.MappingExtractor
> ...

But it made some exception after finishing the extraction, and the extraction-framework did not terminate normally.

> Info; ko; Main Extraction at 18:29.466s for 12 datasets; finished extraction after 1051372 pages with 1.06 ms per page
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> org.apache.jena.riot.RiotNotFoundException: Not found: dataID-tmp.ttl
> 	at org.apache.jena.riot.RDFDataMgr.open(RDFDataMgr.java:835)
> 	at org.apache.jena.riot.RDFDataMgr.open(RDFDataMgr.java:819)
> 	at org.apache.jena.riot.RDFDataMgr.parse(RDFDataMgr.java:664)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:212)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:185)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:123)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:114)
> 	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:76)
> 	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:263)
> 	at org.dbpedia.extraction.mappings.ExtractionMonitor.compareTripleCount(ExtractionMonitor.scala:159)
> 	at org.dbpedia.extraction.mappings.ExtractionMonitor.summarize(ExtractionMonitor.scala:128)
> 	at org.dbpedia.extraction.util.ExtractionRecorder.finalize(ExtractionRecorder.scala:331)
> 	at org.dbpedia.extraction.dump.extract.ExtractionJob.run(ExtractionJob.scala:96)
> 	at org.dbpedia.extraction.dump.extract.Extraction$$anonfun$main$2$$anonfun$1.apply$mcV$sp(Extraction.scala:37)
> 	at org.dbpedia.extraction.dump.extract.Extraction$$anonfun$main$2$$anonfun$1.apply(Extraction.scala:37)
> 	at org.dbpedia.extraction.dump.extract.Extraction$$anonfun$main$2$$anonfun$1.apply(Extraction.scala:37)
> 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
> 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
> 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
> 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Please, let me know how to figure it out.

**Comment by nheist** [comment]
Hey @onlyjiny,
I've just experienced the same error and as a quick fix you can add the following variable assignment to your extraction-properties file:
`
compareDatasetIDs=false
`
By setting this variable to `false`, you will not get any details about differences between individual extraction runs (for me, this was not important at all. So I simply disabled it).

I guess the reason for this error occurring is that the program tries to create a file named `dataID-tmp.ttl` and use that at a later point in time. However, it seems to be creating it in the root folder. Thus, if you do not start the program with the respective access rights, the program might fail to create this file and also fails to read it afterwards. (This is my best guess on how the error occurs, but I didn't analyze it in detail.)

**Comment by JJ-Author** [comment]
fixed in https://github.com/dbpedia/extraction-framework/commit/65d7549dd8d750ee55c995db14c61aa0f0e86e26
