### ISSUE TITLE
Unable to run maven install

### ISSUE THREAD

**Issue by tmlima** [dbpedia/extraction-framework#549]
I am trying to do a maven clean install, but I am receving a message which says I need at least Java8, but on page 
https://github.com/dbpedia/extraction-framework/wiki/Extraction-Instructions
It says Java 7 is necessary.

[INFO] -----------------------< org.dbpedia:extraction >-----------------------
[INFO] Building Parent POM of the DBpedia framework 4.2-SNAPSHOT          [1/7]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ extraction ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (default) @ extraction ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
Detected JDK Version: 1.7.0-80 is not in the allowed range 1.8.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Parent POM of the DBpedia framework 4.2-SNAPSHOT ... FAILURE [  1.753 s]
[INFO] DBpedia Core Libraries ............................. SKIPPED
[INFO] DBpedia Server ..................................... SKIPPED
[INFO] DBpedia Dump Extraction ............................ SKIPPED
[INFO] DBpedia Scripts .................................... SKIPPED
[INFO] Live extraction .................................... SKIPPED
[INFO] Wiktionary Dump 4.2-SNAPSHOT ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.177 s
[INFO] Finished at: 2018-06-09T17:51:36-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (default) on project extraction: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]

this is my maven version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T16:49:05-03:00)
Maven home: C:\Program Files\apache-maven-3.5.3\bin\..
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_80\jre

Can someone help me on that?

**Comment by jimkont** [comment]
Hello,

the framework requires Java 8 to build but seems that you have Java 7

```
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_80\jre
```

Can you upgrade to Java 8 or, if you did already, configure maven to use
the correct Java version?

Cheers,
Dimitris

**Comment by tmlima** [comment]
I installed java 8 and was able to install :)
I recommend you to update the extraction instructions page, for future users.
Thanks!
