### ISSUE TITLE
Newbie: FileNotFoundException: config=download.minimal.properties

### ISSUE THREAD

**Issue by MaherBTA** [dbpedia/extraction-framework#551]
Hi,
after running mvn clean install, I am trying to make my first execution.
but every time I run the script, it doesn't find the configuration file while it exists in the dump folder :
```
../run download config=download.minimal.properties
../run download config=./download.minimal.properties
../run download config=./dump/download.minimal.properties
```

even an absolute path doesn't work. also I am sure that I have the privileges over the files.

**Comment by JJ-Author** [comment]
thanks for your input @interviewBubble. @MaherBTA did that work for you?
I updated the wiki page https://github.com/dbpedia/extraction-framework/wiki/Extraction-Instructions/952606069c5478cb9fa0d037f256317a7d4381d6 and would like to close the issue

**Comment by m1ci** [comment]
ping @MaherBTA all good? can we close the issue?

**Comment by MaherBTA** [comment]
thanks guys, yes you can close the issue
