### ISSUE TITLE
Types of some groups

### ISSUE THREAD

**Issue by lolive** [dbpedia/extraction-framework#553]
Hello.
This query: 
SELECT DISTINCT * WHERE { GRAPH <http://dbpedia.org> { VALUES (?Band0)  {  (<http://dbpedia.org/resource/Australian_Pink_Floyd_Show> )  } ?Band0 ?p ?o
   }} LIMIT 5000
does not return a type "MusicalArtist" or "MusicalGroup".

Comparing to my local instance available here:
http://dbpedia.datao.net/sparql?default-graph-uri=&query=SELECT+DISTINCT+*+WHERE+%7B++%7B+VALUES+%28%3FBand0%29++%7B++%28%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FAustralian_Pink_Floyd_Show%3E+%29++%7D+%3FBand0+%3Fp+%3Fo%0D%0A+++%7D%7D+LIMIT+5000&should-sponge=&format=text%2Fhtml&timeout=0&debug=on

it seems that there is a big regression.

**Comment by mgns** [comment]
Not sure what version of DBpedia your local instance contains, but http://dbpedia.org/resource/Australian_Pink_Floyd_Show redirects to http://dbpedia.org/resource/The_Australian_Pink_Floyd_Show. There you might find the types you are looking for. The reason for that is that Wikipedia articles are constantly changing, which is reflected in DBpedia as well.
