### ISSUE TITLE
Infobox properties output function call as string

### ISSUE THREAD

**Issue by patzomir** [dbpedia/extraction-framework#555]
I ran the latest the extraction framework with the latest mappings. The infobox properties are mostly outputted in this manner:
<http://dbpedia.org/resource/Minsk> <http://dbpedia.org/property/populationUrban> "ParseResult(2101018,None,None)"^^<http://www.w3.org/2001/XMLSchema#integer>

The ParseResult is a case class but maybe there aren't parse objects for integer, double, date etc.
Can someone take a look at it?
Thanks,

**Comment by kurzum** [comment]
compare lines:
https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/mappings/InfoboxExtractor.scala#L203
with 
https://github.com/dbpedia/extraction-framework/blob/master/core/src/main/scala/org/dbpedia/extraction/mappings/InfoboxExtractor.scala#L208

**Comment by kurzum** [comment]
@Vehnem @dies-und-lenes 
Where are the right branches to fix this?

**Comment by kurzum** [comment]
actually @JJ-Author might know better

**Comment by JJ-Author** [comment]
according to @dies-und-lenes this was fixed in the spark branch (https://github.com/dbpedia/extraction-framework/commit/b21589e) which got merged into the master branch and therefore should also work in the master branch.

**Comment by JJ-Author** [comment]
since @patzomir provided no concrete example and it seems to work for our examples I close the issue.
