### ISSUE TITLE
Confusion btw dbo:causalties and dbo:casualties 

### ISSUE THREAD

**Issue by exhumea** [dbpedia/extraction-framework#560]
There is a mix between those two properties whereas only _dbo:casualties_ should exist.
For example see : [Battle of the Somme](http://dbpedia.org/page/Battle_of_the_Somme)

**Comment by JJ-Author** [comment]
Hi. As far as i can see this has nothing to do with the extraction framework. Please fix the error in the community-driven and -maintained mappings. See http://mappings.dbpedia.org/index.php/Main_Page to fixi it and how to get started with editing mappings. You can also have a look here https://github.com/dbpedia/mappings-tracker and discuss whether the property dbo:casualties should be deleted in general.
