### ISSUE TITLE
strange triple and long IRI

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/extraction-framework#563]
downloads.dbpedia.org/tmpdev/diffs/new2/generic-spark/citation-data/2018.10.16/citation-data-2018.10.16_enwiki.adds.ttl:790374

[triple.txt](https://github.com/dbpedia/extraction-framework/files/2542481/triple.txt)

**Comment by kurzum** [comment]
Closing this, because it is tackled systematically with https://forum.dbpedia.org/t/new-ci-tests-on-dbpedia-releases/77/3
