### ISSUE TITLE
Lot's of invalid triples produced, e.g. whitespace in uri

### ISSUE THREAD

**Issue by kurzum** [dbpedia/extraction-framework#575]
The parselogs are here:
http://downloads.dbpedia.org/temporary/parselogs/
(wikidata still missing)
tool was rapper version 2.014. and we parsed all 5 or 6 last versions of the new releases, so there are many duplicate errors in it.
@Vehnem is producing  more specific parselogs for each artifact for the coming versions.

**Comment by kurzum** [comment]
(generic parselog is still copying, will be there in some hours)

**Comment by JJ-Author** [comment]
see #563 and #562

**Comment by kurzum** [comment]
Closing this, because it is tackled systematically with https://forum.dbpedia.org/t/new-ci-tests-on-dbpedia-releases/77/3
