### ISSUE TITLE
IPA template not resolved when using AbstractExtractorWikipedia (NIF extraction)

### ISSUE THREAD

**Issue by dies-und-lenes** [dbpedia/extraction-framework#579]
Extraction of 

``The Renaissance (UK: /rɪˈneɪsəns/, US: /ˈrɛnəsɑːns/)[a] is a period in European history...``

from the original html of the Wikipage will lead to the result: 

``The Renaissance (UK: , US: ) is a period in European history... ``

Reproduction: configure the server to use AbstractExtractorWikipedia, which is making use of the NIF extraction classes in the package org.dbpedia.extraction.nif  (path: ``core/src/main/scala/org/dbpedia/extraction/nif/`` )

**Comment by kurzum** [comment]
Closing issue without test, as described in #716
