### ISSUE TITLE
Duplicate resource names with underscore 

### ISSUE THREAD

**Issue by kliegr** [dbpedia/extraction-framework#589]
DBpedia instance_types_en.ttl contains duplicate entries, which are distinguished only by _[number] suffix. This is present both in 2016_04 dump as well as in live DBpedia.
E.g.
http://dbpedia.org/resource/Ada_Lovelace
http://dbpedia.org/resource/Ada_Lovelace__1

Both resources are connected via dbo:personFunction, for other resources the connection is a different property.

The 2016_04 dump additionally contains 
http://dbpedia.org/resource/Ada_Lovelace__2 ... 12

What is the semantics of this possible duplicate entries?

**Comment by JJ-Author** [comment]
This seems like a question for forum.dbpedia.org

**Comment by kurzum** [comment]
@kliegr can you take this to https://forum.dbpedia.org  ?

**Comment by kurzum** [comment]
Done as per https://forum.dbpedia.org/t/duplicate-resource-names-with-underscore/104/4
