### ISSUE TITLE
Unescaped single quote in IRI 

### ISSUE THREAD

**Issue by elad-shaked** [dbpedia/extraction-framework#629]
Line 8857676 in `redirects_lang=en.ttl`:
```
<http://dbpedia.org/resource/Wheelchair_tennis_at_the_2008_Summer_Paralympics_-_Women's_doubles> <http://dbpedia.org/ontology/wikiPageRedirects> <http://dbpedia.org/resource/Wheelchair_tennis_at_the_2008_Summer_Paralympics_–_Women's_Doubles> .
```
Wikipedia page URL obviously escapes: https://en.wikipedia.org/wiki/Wheelchair_tennis_at_the_2008_Summer_Paralympics_%E2%80%93_Women%27s_Doubles

**Comment by JJ-Author** [comment]
I do not understand. What is the issue? 
I checked the triple with 
https://www.w3.org/2015/03/ShExValidata/
http://akswnc7.informatik.uni-leipzig.de:8088/
http://ttl.summerofcode.be/
and http://sparql.org/iri-validator.html

all reporting that this is correct.
`curl "https://en.wikipedia.org/wiki/Wheelchair_tennis_at_the_2008_Summer_Paralympics_–_Women's_Doubles"` return html also perfectly fine.

Moreover, please provide the full version identifier of the file in the future.

**Comment by elad-shaked** [comment]
Sorry, my bad. The problem was with RDF4J
