### ISSUE TITLE
Dbpedia extraction framework - mvn install error

### ISSUE THREAD

**Issue by Alizeeshanhaider21** [dbpedia/extraction-framework#667]
anam@anam-Y11C:~/Downloads/Downloads/extraction-framework-master$ mvn install
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 7 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 7 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Parent POM of the DBpedia framework                                [pom]
[INFO] DBpedia Core Libraries                                             [jar]
[INFO] DBpedia Scripts                                                    [jar]
[INFO] DBpedia Dump Extraction                                            [jar]
[INFO] DBpedia Server                                                     [jar]
[INFO] Live extraction                                                    [jar]
[INFO] Wiktionary Dump                                                    [jar]
[INFO] 
[INFO] -----------------------< org.dbpedia:extraction >-----------------------
[INFO] Building Parent POM of the DBpedia framework 4.2-SNAPSHOT          [1/7]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (default) @ extraction ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (doc) @ extraction ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (process-resources) @ extraction ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (compile) @ extraction ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:testCompile (test-compile) @ extraction ---
[INFO] No sources to compile
[INFO] 
[INFO] >>> maven-source-plugin:3.1.0:jar (attach-sources) > generate-sources @ extraction >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (default) @ extraction ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (doc) @ extraction ---
[INFO] No sources to compile
[INFO] 
[INFO] <<< maven-source-plugin:3.1.0:jar (attach-sources) < generate-sources @ extraction <<<
[INFO] 
[INFO] 
[INFO] --- maven-source-plugin:3.1.0:jar (attach-sources) @ extraction ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ extraction ---
[INFO] Installing /home/anam/Downloads/Downloads/extraction-framework-master/pom.xml to /home/anam/.m2/repository/org/dbpedia/extraction/4.2-SNAPSHOT/extraction-4.2-SNAPSHOT.pom
[INFO] 
[INFO] --------------------< org.dbpedia.extraction:core >---------------------
[INFO] Building DBpedia Core Libraries 4.2-SNAPSHOT                       [2/7]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (default) @ core ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:add-source (attach-docs-sources) @ core ---
[INFO] Add Source directory: /home/anam/Downloads/Downloads/extraction-framework-master/core/src/main/scala
[INFO] Add Test Source directory: /home/anam/Downloads/Downloads/extraction-framework-master/core/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.2.0:compile (doc) @ core ---
[INFO] /home/anam/Downloads/Downloads/extraction-framework-master/core/src/main/java:-1: info: compiling
[INFO] /home/anam/Downloads/Downloads/extraction-framework-master/core/src/main/scala:-1: info: compiling
[INFO] Compiling 287 source files to /home/anam/Downloads/Downloads/extraction-framework-master/core/target/classes at 1610715481919
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[ERROR] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1387)
[ERROR] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1053)
[ERROR] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
[ERROR] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[ERROR] 	at scala.tools.nsc.Driver.process(Driver.scala:51)
[ERROR] 	at scala.tools.nsc.Driver.main(Driver.scala:64)
[ERROR] 	at scala.tools.nsc.Main.main(Main.scala)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[ERROR] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Parent POM of the DBpedia framework 4.2-SNAPSHOT:
[INFO] 
[INFO] Parent POM of the DBpedia framework ................ SUCCESS [  1.328 s]
[INFO] DBpedia Core Libraries ............................. FAILURE [  1.597 s]
[INFO] DBpedia Scripts .................................... SKIPPED
[INFO] DBpedia Dump Extraction ............................ SKIPPED
[INFO] DBpedia Server ..................................... SKIPPED
[INFO] Live extraction .................................... SKIPPED
[INFO] Wiktionary Dump .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.960 s
[INFO] Finished at: 2021-01-15T12:58:02Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:compile (doc) on project core: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :core

-----------------------------------------------------------------------------------------------------------------------------------------------------------

anam@anam-Y11C:~$ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

anam@anam-Y11C:~$ echo $JAVA_HOME 
/usr/lib/jvm/default-java

anam@anam-Y11C:~$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.9.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-54-generic", arch: "amd64", family: "unix"

anam@anam-Y11C:~$ echo  $M2_HOME 
/opt/maven

anam@anam-Y11C:~$ scala -version
Scala code runner version 2.11.12 -- Copyright 2002-2017, LAMP/EPFL

anam@anam-Y11C:~$ git --version
git version 2.25.1

----------------------------------------------------------------------------------------------------------------------------------------------------
anyone can help me please to fix above errors. i also tried jdk 8 but having same issue

**Comment by Vehnem** [comment]
Hey, have a look at https://github.com/dbpedia/extraction-framework/blob/master/documentation/quickstart.md
You need to use Java 8 instead of Java 11.
If you want to change your JDK quickly, I can recommend https://sdkman.io/

**Comment by Alizeeshanhaider21** [comment]
> Hey, have a look at https://github.com/dbpedia/extraction-framework/blob/master/documentation/quickstart.md
> You need to use Java 8 instead of Java 11.
> If you want to change your JDK quickly, I can recommend https://sdkman.io/
> [EDIT]
> 
> > anyone can help me please to fix above errors. i also tried jdk 8 but having same issue
> 
> pls, make sure maven is using the correct version setting "JAVA_HOME", because the error
> 
> > error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
> 
> usually refers to this problem




is my maven version incorrect?

**Comment by Alizeeshanhaider21** [comment]
is my maven version incorrect?

**Comment by Alizeeshanhaider21** [comment]
and its environment? can uh clerify me plz?

**Comment by JJ-Author** [comment]
@Alizeeshanhaider21 why did you not use the appropriate issue template? are there technical issues or is something unclear?

**Comment by Alizeeshanhaider21** [comment]
> @Alizeeshanhaider21 why did you not use the appropriate issue template? are there technical issues or is something unclear?
the issue is resolved, but now I am stuck on a Database connection. I face problems with Mangodb Connection. Everything that is you provide us on Github. I follow all these commands but not resolve…!

Mapping link, that I follow
https://github.com/dbpedia/mappings-ui

**Comment by kurzum** [comment]
> anyone can help me please to fix above errors. i also tried jdk 8 but having same issue

closed issue, as only information was given about running it with java 11, but not with Java 8. Framework needs Java 8 to run
