### ISSUE TITLE
Snorql needs https update

### ISSUE THREAD

**Issue by kurzum** [dbpedia/extraction-framework#675]
@pkleef related to snorql, not sure, if this is your fix or someone needs to dig into the dbpedia-vad. Please advise. 

# Where did the problem occur (e.g. dbpedia.org/sparql, lookup, spotlight)?
> Please give the full URL, if possible
reported here: https://forum.dbpedia.org/t/new-dbpedia-website/911

see [link](https://dbpedia.org/snorql/?query=SELECT+distinct+%3Fsoccerplayer+%3FcountryOfBirth+%3Fteam+%3FcountryOfTeam+%3Fstadiumcapacity%0D%0A%7B+%0D%0A%3Fsoccerplayer+a+dbo%3ASoccerPlayer+%3B%0D%0A+++dbo%3Aposition%7Cdbp%3Aposition+%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2FGoalkeeper_%28association_football%29%3E+%3B%0D%0A+++dbo%3AbirthPlace%2Fdbo%3Acountry*+%3FcountryOfBirth+%3B%0D%0A+++%23dbo%3Anumber+13+%3B%0D%0A+++dbo%3Ateam+%3Fteam+.%0D%0A+++%3Fteam+dbo%3Acapacity+%3Fstadiumcapacity+%3B+dbo%3Aground+%3FcountryOfTeam+.+%0D%0A+++%3FcountryOfBirth+a+dbo%3ACountry+%3B+dbo%3ApopulationTotal+%3Fpopulation+.%0D%0A+++%3FcountryOfTeam+a+dbo%3ACountry+.%0D%0AFILTER+%28%3FcountryOfTeam+%21%3D+%3FcountryOfBirth%29%0D%0AFILTER+%28%3Fstadiumcapacity+%3E+30000%29%0D%0AFILTER+%28%3Fpopulation+%3E+10000000%29%0D%0A%7D+order+by+%3Fsoccerplayer)

# Problem description 
> Please state the nature of your technical emergency.

after the general https upgrade it is https://dbpedia.org/snorql using http://dbpedia.org/sparql
Jenssteckhan identified it as a browser block, i.e. calling a http url from htts

# Expected behaviour
> What did you expect? 

probably just need to add an `s` somewhere in the snorql code.

# Request/Reproduction
> Give the link or request, so the problem can be reproduced. Ideally, this would be a unix `curl` command.

any query

![Screenshot from 2021-02-03 20-37-15](https://user-images.githubusercontent.com/900758/106799537-a9b3ef00-665f-11eb-9e1e-ac5966d9e3d8.png)

**Comment by openlink** [comment]
The snorql code is not part of the dbpedia package, but installed standalone. It is a very old version, though the 'official' git tree at https://github.com/kurtjx/SNORQL is not much newer. 

For now i made 2 changes to the local code base on dbpedia.org to allow it to work in an https based environment.

**Comment by pkleef** [comment]
Fixed
