### ISSUE TITLE
How to get all data from dbpedia page (Using Python and SPARQL) #Question

### ISSUE THREAD

**Issue by dasisro-trendlab** [dbpedia/extraction-framework#679]
Hello everyone,
I'm trying to get all the data from https://dbpedia.org/page/Asturias (Abstract, Place, Areacode...etc) using python but without success.
I tried with SPARQL (and Python) making some requests and the result was the same. Does someone know if there is a way to get the all data in a request?
Thanks very much in advance,
David

**Comment by kurzum** [comment]
Hi @dasisro-trendlab,
this seems to be like a support request. Would you mind posting it to forum.dbpedia.org ?
The answer could benefit many people with the same problem, but if we close the issue here it will be lost and also not indexed in google well.
Thanks, 
Sebastian

**Comment by dasisro-trendlab** [comment]
Yes you're right @kurzum, sorry. I'll put it on the forum.

Thanks
