### ISSUE TITLE
wikipedia XML Dumps

### ISSUE THREAD

**Issue by HammadAnwar180** [dbpedia/extraction-framework#683]
we run that command to Download Wikipedia XML Dumps for dependencies

cd dump
../run download download.10000.properties

And we face that type of errors.

[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.0:run (default-cli) on project dump: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by Vehnem** [comment]
Hi, it seems like you deleted the Issue Template.

> *Please fill out or post:*
 - **Extraction:** (commit hash): 
 - **OS:** 
 - **Java SDK Version** (java --version):
 - **Maven version** (mvn --version):
 
80% of the time, these issues relate to incompatible JAVA versions

**Comment by HammadAnwar180** [comment]
![Screenshot from 2021-02-27 23-18-23](https://user-images.githubusercontent.com/50082104/109396181-28940300-7952-11eb-803a-275f3f9572f8.png)
