### ISSUE TITLE
Multiple wikipedia info boxes merged into one dbpedia resource

### ISSUE THREAD

**Issue by mubashar1199** [dbpedia/extraction-framework#709]
In the templatemapping.scala file in dbpedia extraction framework, if wiki page have more than one infoboxes, they are merged into single dbpedia resource. Due to this alot of inconsistent data is populated in dbpedia for example:
1. Person having more than one birthDate.
2. Properties of one person in wikipedia is assigned to other person in the dbpedia.

Please see the wikipedia and dbpedia resource Helene_Demuth or Karen_McCarron as an example. In dbpedia Karen is mentioned as self parent due to merging of infoboxes. Several such problems exists due to merging of infoboxes.

I am working on this issue to remove it, Please assign me to this issue.

Thanks

**Comment by JJ-Author** [comment]
Do you have any idea how to approach this? I do not really have a good one except for filtering the infobox by its label (comparing with page title and ignoring the incorrect infobox). I would suggest to start with an analysis how many entities are actually affected.

**Comment by jlareck** [comment]
Also, there is a discussion in issues related to this problem I guess. Maybe you can check it: https://github.com/dbpedia/extraction-framework/issues/17 . It seems to me that there was discussed almost the same problem

**Comment by mubashar1199** [comment]
I have cloned the project again and ran the tests successfully, but after adding any new page in the uris.lst and running ./createMinidump.sh, the test fails again. Please see the following page and test report.

//test page
https://en.wikipedia.org/wiki/Helene_Demuth

//test report
![testreport](https://user-images.githubusercontent.com/54760478/131240246-e3bb85a5-83a2-401e-a2c9-4fcc82783409.PNG)

**Comment by mubashar1199** [comment]
I think this test have something to do with it
![isbntest](https://user-images.githubusercontent.com/54760478/131240511-f74dae04-19d5-4ea7-b4c2-d5a82310ca99.PNG)

**Comment by mubashar1199** [comment]
I deleted the isbn test from testGroups.csv file and tests ran successfully, so there is something wrong with this test, this is also related i thinks https://github.com/dbpedia/extraction-framework/issues/625

**Comment by jlareck** [comment]
Okay, I will check this test. Also, if you haven't already made too many changes could you please switch to dev branch, and make changes on it? Dev branch has more new changes that were not merged with masters but I guess it will be merged soon. 
And for testing using SHACL tests in dev branch, you need to add tests names to https://github.com/dbpedia/extraction-framework/blob/dev/dump/src/test/resources/shacl-test-groups.csv table and mark them with `yes` (to disable the test use `no` in `Productive` column)

**Comment by JJ-Author** [comment]
a general remark you are sending around a lot of images, i think it would be better when you just create a branch (fork) instead so that everybody can easily reproduce. then there is no need to ask, what is in there, can you send me the input of that, etc.

**Comment by mubashar1199** [comment]
I have created the new branch and after solving the issue, i have created a pull request as per instructions mentioned [here](https://github.com/dbpedia/extraction-framework/), sonarcloud quality gate  failed and there is a conflicting file issue which is testGroups.csv. What to do further?

**Comment by jlareck** [comment]
Great, thank you @mubashar1199! I will review your fix
