### ISSUE TITLE
problem with datatype of geo coordinates

### ISSUE THREAD

**Issue by D063520** [dbpedia/extraction-framework#712]
# Issue validity
dbpedia core

# Error Description
https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=select+*+where%0D%0A%7B%0D%0A%3Fs+%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23geometry%3E+%3Fo+%0D%0A%7D+limit+100&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on
the following triples have a strange datatype

# Pinpointing the source of the error
not sure where it contains

> Wrong triples RDF snippet 
  ``` 
  "POINT(-49.412799835205 -28.98390007019)"^^<http://www.openlinksw.com/schemas/virtrdf#Geometry>
  ``` 
> Expected / corrected RDF outcome snippet 
  ``` 
  "POINT(-49.412799835205 -28.98390007019)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>
  ```
>Example DBpedia resource URL(s)
```

```
> Other

**Comment by kurzum** [comment]
@D063520 this triple seems to be added on top of what is in the dumps. 
See https://databus.dbpedia.org/dbpedia/generic/geo-coordinates/2021.06.01
```
<http://dbpedia.org/resource/'Arab_al-Rashayida> <http://www.georss.org/georss/point> "31.753055555555555 35.3475" .
<http://dbpedia.org/resource/'Arab_al-Rashayida> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing> .
<http://dbpedia.org/resource/'Arab_al-Rashayida> <http://www.w3.org/2003/01/geo/wgs84_pos#lat> "31.753055555555555"^^<http://www.w3.org/2001/XMLSchema#float> .
<http://dbpedia.org/resource/'Arab_al-Rashayida> <http://www.w3.org/2003/01/geo/wgs84_pos#long> "35.3475"^^<http://www.w3.org/2001/XMLSchema#float> .

```
Then in the store this is added: 
```
<http://dbpedia.org/resource/\u0027Arab_al-Rashayida>	<http://www.w3.org/2003/01/geo/wgs84_pos#geometry>	"POINT(35.347499847412 31.75305557251)"^^<http://www.openlinksw.com/schemas/virtrdf#Geometry> .
```
However, `http://www.w3.org/2003/01/geo/wgs84_pos#geometry` does not exist in the first place, so the datatype is also not given. 
@pkleef Do you knwo where this extra triple comes from?

**Comment by pkleef** [comment]
Virtuoso currently adds that triple as part of its GEO index

**Comment by D063520** [comment]
Hi, after our discussion yesterday, we grab the geo-coordinates directly from <http://www.w3.org/2003/01/geo/wgs84_pos#lat>, <http://www.w3.org/2003/01/geo/wgs84_pos#long> so it is fine!
