### ISSUE TITLE
problem with build

### ISSUE THREAD

**Issue by ghost-2362003** [dbpedia/extraction-framework#769]
![Screenshot 2024-12-13 132507](https://github.com/user-attachments/assets/5e88e561-c723-4411-a086-ee12d47f5363)

the file mentioned is deleted and i have specified it to be built using java 8 
yet this error keeping popping up
how to mitigate this issue

**Comment by m1ci** [comment]
I think you are still not using Java 8.

Milan

**Comment by JJ-Author** [comment]
obviously @ghost-2362003  is using jdk 17. I am closing this now, since I gave very specific instructions how to report the bug.
feel free to open again when every requested information is provided by @ghost-2362003.
